### ISSUE TITLE
Migrare albo di Altavilla Milicia da kimono a gsheet

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#108]

**Comment by aborruso** [comment]
Aggiornato e risolto. Non c'è nulla da modificare, l'URL sorgente è rimasto lo stesso

**Comment by matteoscire** [comment]
Perfetto!
Grazie

2016-03-09 15:08 GMT+01:00 Andrea Borruso notifications@github.com:

> Closed #108 https://github.com/aborruso/albo-pop/issues/108.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aborruso/albo-pop/issues/108#event-583318531.

## 

Matteo Scirè
