### ISSUE TITLE
realizzare un tutorial sulla gestione di feed su cellulariu android

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#109]

**Comment by aborruso** [comment]
@cristianolongo hai chiuso perché il tutorial è pronto? Se sì, inserisci link al tutorial?

**Comment by cristianolongo** [comment]
No ho chiuso con wontfix

**Comment by aborruso** [comment]
On 5 September 2016 at 12:48, Cristiano Longo notifications@github.com
wrote:

> No ho chiuso con wontfix

Pensi comunque che sia utile?? Se sì, me lo autoassegno

---

Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

---

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by cristianolongo** [comment]
E' difficile anche perchè si sono diversi client. Si fa prima ad aiutare 
le persone di presenza. Non credo sia utile.
