### ISSUE TITLE
Aggiungere Altavilla Milicia

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#11]
Feed RSS http://feeds.feedburner.com/AlboPopAltavillaMilicia

**Comment by aborruso** [comment]
Creato e attivato canale Telegram: https://telegram.me/AlboPretorioAltavillaMilicia

Test in corso con @matteoscire

**Comment by matteoscire** [comment]
Ho visto che il Comune oggi ha pubblicato diversi avvisi ma sul canale non è arrivato nulla.

**Comment by aborruso** [comment]
@matteoscire work in progress. E' lunedì e sono stato sommerso. Ho attivato tutto, ma devo fare una correzione. Sorry

**Comment by aborruso** [comment]
@matteoscire ma perché scrivi "diversi"? Solo una pubblicazione in albo oggi ad Altavilla. O sto sbagliando sito?
![2015-12-14_21h35_04](https://cloud.githubusercontent.com/assets/30607/11793215/93098e82-a2aa-11e5-84c3-24653793eec1.png)

**Comment by matteoscire** [comment]
Scusa. Mi sono sbagliato. Hai ragione era solo un avviso.

**Comment by matteoscire** [comment]
Su Telegram non viene visualizzata la data.

**Comment by aborruso** [comment]
La data è in testa ai messaggi del giorno
![2015-12-16_10h59_39](https://cloud.githubusercontent.com/assets/30607/11837939/2d48b59c-a3e4-11e5-92eb-9f0a92af185d.png)
