### ISSUE TITLE
Una bella comunicazione di servizio: nasce albopop.it

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#110]
Buon pomeriggio,
dopo mesi finalmente ho attivo il reindirizzamento del dominio [http://albopop.it](http://albopop.it) verso il nostro repo.

Era necessario e utile. 

Saluti

**Comment by cristianolongo** [comment]
grande! bella sorpresa.

**Comment by mfortini** [comment]
Ottima notizia!

Il gio 10 mar 2016 17:21 Cristiano Longo notifications@github.com ha
scritto:

**Comment by giuragu** [comment]
Bella notizia!
Possiamo darne già conto dall'Alpe alle Piramidi?

**Comment by aborruso** [comment]
2016-03-10 18:36 GMT+01:00 giuragu84 notifications@github.com:

> Bella notizia!
> Possiamo darne già conto dall'Alpe alle Piramidi?

Vediamo se riesco a scrivere annuncio ufficiale e poi eventualmente tutti
liberi?

## 

 Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

## 

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by giuragu** [comment]
@aborruso mi pare giustissimo...attenderei tuo annuncio ufficiale
