### ISSUE TITLE
Abbonarsi a RSS filtrando per parola chiave

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#111]
Buongiorno,
quanto sarebbe comodo iscriversi ai feed di un albo che filtri i soli elementi che contengono la sola parola chiave "confisca" (idea di @cristianolongo )? O "web"? O "Consiglio comunale"?

Lo [script](https://github.com/aborruso/albo-pop/tree/master/code/GDriveGeneric) creato da @mfortini è di enorme comodità e facilità di utilizzo.
Inoltre si poggia su un servizio esterno che avrà vita lunga, ricco di funzioni e molto ben documentato, ovvero "google app script".
Ecco, sembra che sia molto facile realizzare un feed RSS **filtrato per parola chiave** :)

Gli URL attuali nativi di questi feed sono qualcosa come:

```
https://script.google.com/macros/s/AKfycby.../exec
```

Tramite google app script sembra (è tutto ancora da testare) che si possano utilizzare gli `URL parameters` e generare banalmente un RSS filtrato, con un URL di questo tipo:

```
https://script.google.com/macros/s/AKfycby.../exec?ricerca=confisca
```

Lo script è da modificare ma la cosa mi sembra veramente dirompente.

La documentazione è qui https://developers.google.com/apps-script/guides/web#url_parameters

**Comment by cristianolongo** [comment]
Ciao, io per ora sto filtrando sul client di posta, come indicato nel 
tutorial https://github.com/aborruso/albo-pop/wiki/ThunderbirdRSS.
Penso che anche realizzare uno script PHP che prenda in input un feed 
rss per generarne il corrispettivo filtrato sia abbastanza facile da 
realizzare (ma per ora non è nei miei piani).

CL

**Comment by mfortini** [comment]
Confermo Andy che ho provato ad aggiungere parametri a un GS ed è davvero
semplice come dici, si può fare sicuramente, lo mettiamo in piedi!

Il ven 11 mar 2016 11:55 Cristiano Longo notifications@github.com ha
scritto:

**Comment by mfortini** [comment]
Aggiunta la possibilità di filtrare passando una parola con la chiave "ricerca" come indicato nella issue. Commit 83916c0

**Comment by aborruso** [comment]
Ok, mi metto a piangere :) 

Ad esempio tutti i "bando" dell'albo dell'università di Palermo: [https://script.google.com/macros/s/AKfycbymolXXVWIjvXHg2tunSW0pkylmtYD9NTJ204tHFyZJzJn8NFU7/exec?ricerca=bando](https://script.google.com/macros/s/AKfycbymolXXVWIjvXHg2tunSW0pkylmtYD9NTJ204tHFyZJzJn8NFU7/exec?ricerca=bando)

Gran bella cosa @mfortini
