### ISSUE TITLE
Filtrare RSS per regexp

### ISSUE THREAD

**Issue by mfortini** [aborruso/albo-pop#119]
Permettere url come
https://script.google.com/macros/s/AKfycbxhj2Y4sDjVNHogniNljqMHxRAsIe1TI_jBp01wCdDP5DeZEVYA/exec?regexp=/.*illumina.*/
https://script.google.com/macros/s/AKfycbxhj2Y4sDjVNHogniNljqMHxRAsIe1TI_jBp01wCdDP5DeZEVYA/exec?regexp=/.*illumina.*/i
https://script.google.com/macros/s/AKfycbxhj2Y4sDjVNHogniNljqMHxRAsIe1TI_jBp01wCdDP5DeZEVYA/exec?regexp=.*illumina.*

**Comment by mfortini** [comment]
Implementato in commit 88f6474

**Comment by aborruso** [comment]
@mfortini l'ho provato con calma stamattina ed è veramente di grandissima comodità

Ora tocca lavorare sulla documentazione (aiuto :)  )

E grazie
