### ISSUE TITLE
Creare blog post per evento di Catania

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#120]
Ciao @cristianolongo lo crei per favore un piccolo blog post sull'[evento](https://www.facebook.com/events/1133850986634756/) che stai organizzando?

Qui c'è la [guida](http://albopop.it/come_pubblicare_post_su_albopop/) su come pubblicare un post.

Grazie

**Comment by cristianolongo** [comment]
su master o gh-pages?

**Comment by aborruso** [comment]
E' meglio che lo scrivo, hai ragione. Su gh-pages 

Si vede comunque nell'anteprima del filmato e nel filmato.

**Comment by cristianolongo** [comment]
Ho messo il post su gh-pages

**Comment by aborruso** [comment]
@cristianolongo pubblicato http://albopop.it/Aperitivo-POP-Catania/

Non lor era ancora, perché nel nome del file devi inserire la data di pubblicazione (mentre c'era  una data nel futuro, quella dell'evento)

**Comment by cristianolongo** [comment]
Ahhhhhhh
Il 18/mar/2016 09:13 AM, "Andrea Borruso" notifications@github.com ha
scritto:
