### ISSUE TITLE
Creare una presentazione sul wiki per l'albo social

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#122]

**Comment by aborruso** [comment]
@cristianolongo ma mi sembra di capire che ci sia già funzionante qualcosa.

Un URL in anteprima per tutti noi??  :)

**Comment by cristianolongo** [comment]
E' un albo che come URL ha quella di una pagina web creata on the fly 
col pulsante share on facebook. La URL del feed dell'albo pop social del 
comune di catania è 
http://dev.opendatasicilia.it/albopop/catania/alboct2RSS-social.php.

**Comment by cristianolongo** [comment]
https://github.com/aborruso/albo-pop/wiki/Albi-POP-Social

Aggiunto anche alle FAQ.
