### ISSUE TITLE
Albo POP Ostuni (BR)

### ISSUE THREAD

**Issue by paolone69** [aborruso/albo-pop#125]
Bellissimo e utilissimo, complimenti. Vorrei farne uno anche per l'albo pretorio del mio comune: Ostuni in provincia di Brindisi. Mi date una mano? Questo l'indirizzo dell'albo  http://dgegovpa.it/ostuni/Albo/Albo.aspx
Grazie mille.
Paolo

**Comment by simoneversienti** [comment]
@aborruso posso dare una mano io con IFTTT

**Comment by aborruso** [comment]
@paolone69 @simoneversienti ecco una prima versione del feed RSS:
[https://script.google.com/macros/s/AKfycbzONH3Opct2j4rI03fWg0y94YZRZFlcit-EaOr00DLx1wHEX-M/exec](https://script.google.com/macros/s/AKfycbzONH3Opct2j4rI03fWg0y94YZRZFlcit-EaOr00DLx1wHEX-M/exec)

Al momento pesco solo il link al primo PDF presente.

**Comment by paolone69** [comment]
Grazie mille @aborruso  e @simoneversienti

**Comment by simoneversienti** [comment]
@aborruso io e @paolone69 abbiamo notato che c'è un problema con il feed RSS, l'ultima inserzione è quella del 23 marzo...da allora non si è più aggiornato

**Comment by aborruso** [comment]
@simoneversienti @paolone69 c'era un problema nello script. Adesso sembra che si sia aggiornato https://script.google.com/macros/s/AKfycbzONH3Opct2j4rI03fWg0y94YZRZFlcit-EaOr00DLx1wHEX-M/exec
