### ISSUE TITLE
Albo Pop Barletta(BT)

### ISSUE THREAD

**Issue by Rinux83** [aborruso/albo-pop#128]
Ciao a tutti, 
riporto qui l'esperienza con l'albo pretorio del comune di Barletta:
http://0penyourm1nd.blogspot.it/2016/03/liberiamo-lalbo-pretorio-del-comune-di.html

**Comment by aborruso** [comment]
wow @Rinux83 non sai che cosa piacevole è vedere che qualcuno dall'esterno ha riutilizzato "pezzi" creati per albopop. Complimenti!!

Peccato che questo Albo sia protetto da cookie di sessione e non ci sia modo di generare una chiamata che ti faccia aprire la pagina relativa al singolo atto.

Bravo

**Comment by aborruso** [comment]
@Rinux83 Barletta è in elenco http://albopop.it/comune/barletta/

Due domande:
- come ti chiami?
- che URL vuoi che inserisca in corrispondenza del tuo nome?

Posso pubblicare il tuo post in copia nel blog di albopop e citando la fonte?

**Comment by Rinux83** [comment]
@aborruso Si certo, pubblica pure
Mi chiamo Ruggiero Dilillo, puoi anche lasciare così come hai già fatto in corrispondenza del mio nome

**Comment by aborruso** [comment]
Eccolo Ruggiero [http://albopop.it/apri-e-condividi-le-tue-conoscenze/](http://albopop.it/apri-e-condividi-le-tue-conoscenze/)  :)
