### ISSUE TITLE
Sezione FAQ nel sito

### ISSUE THREAD

**Issue by giuragu** [aborruso/albo-pop#13]
Aggiungere una sezione FAQ nel sito attuale o nel futuro sito per chiarire i dubbi e i problemi più frequenti per gli utenti in generale.

**Comment by aborruso** [comment]
@giuragu84 inizia a scriverla qui: https://github.com/aborruso/albo-pop/wiki/FAQ

Farò poi il primo "trasferimento" e in seguito ti mostrerò come essere autonomo :)

P.S. io oggi nel wiki ho iniziato a mettere [questo](https://github.com/aborruso/albo-pop/wiki/Utilizzare-Google-Drive-Sheet-per-estrarre-dati-da-una-pagina-web).

**Comment by giuragu** [comment]
@aborruso yes! :)
