### ISSUE TITLE
AlboPop comuni di Giovinazzo e Molfetta e modifiche nello script

### ISSUE THREAD

**Issue by sputnik63** [aborruso/albo-pop#134]
Ciao a tutti.
Ho appena aggiunto gli AlboPop dei comuni di Giovinazzo e Molfetta entrambi in prov. di BA
Analogamente al conterraneo barlettano ho avuto il problema di non riuscire ad accedere direttamente al link del singolo documento pubblicato per come è fatta la pagina web di entrambi gli albi.
Poichè nello script di Fortini è possibile costruire il _guid_ del singolo item del feed e poiché è sufficiente che questo sia univoco per l'univocità di ogni item (anche se il _link_ è uguale per tutti), ho aggiunto allo script una piccola funzioncina che mi genera un hash MD5 che accodo al titolo per generare il _guid_ (anche se credo sia sufficiente avere come _guid_ il solo hash, ma non ho provato).
La funzioncina è questa:

```
String.prototype.mD5 = function() {
    var signature = Utilities.computeDigest(Utilities.DigestAlgorithm.MD5, this, Utilities.Charset.UTF_8);
    var signatureStr = '';
    for (i = 0; i < signature.length; i++) {
        var byte = signature[i];
        if (byte < 0) {
            byte += 256;
        }
        var byteStr = byte.toString(16);
        // Ensure we have 2 chars in our byte, pad with 0
        if (byteStr.length == 1) {
            byteStr = '0'+byteStr;
        }
        signatureStr += byteStr;
    }   
    return signatureStr;
};
```

che poi uso nello script come:
`var codice_univoco = titolo.mD5();
`

per poi accodarlo al guid con:
`guid: myguid+"_"+codice_univoco,
`

Ovviamente il suo uso è migliorabile. Due pubblicazioni con stesso titolo ed es. "Estate 2016" avrebbero lo stesso hash con tutto quello che ne consegue. Al momento questo caso non si è verificato ma penso sia meglio affinarne l'uso comunque.

Francesco

**Comment by aborruso** [comment]
Grazie mille @sputnik63. Faccio un ping a @mfortini solo per conoscenza.

**Comment by aborruso** [comment]
Dai un occhio a #138
