### ISSUE TITLE
Richiesta creazione alboPOP per Barcellona Pozzo di Gotto

### ISSUE THREAD

**Issue by salvob84** [aborruso/albo-pop#137]
Ciao a tutti

sono Salvo ed inserisco questa richiesta su indicazione di Andrea

l'URL dell'albo è http://88.41.51.242/gesdelidet/dadabik_4.2/program_files/index.php?table_name=atti&function=search&where_clause=&page=0&order=datapu&order_type=DESC

Grazie

**Comment by aborruso** [comment]
Ciao @salvob84 ho iniziato a  impostare l'estrazione dei dati e la puoi vedere qui [https://docs.google.com/spreadsheets/d/130KzQALVXDDGRAvtKqOJrA8XEFWgRnLOLbHw0d4kTRM/edit?usp=sharing](https://docs.google.com/spreadsheets/d/130KzQALVXDDGRAvtKqOJrA8XEFWgRnLOLbHw0d4kTRM/edit?usp=sharing).

Ho tirato fuori anche una prima versione di RSS [https://script.google.com/macros/s/AKfycbzDyOP18Jwt0k6VSHskxHsFKdv9V47yYzQT8LWwgicwVeWGerE/exec](https://script.google.com/macros/s/AKfycbzDyOP18Jwt0k6VSHskxHsFKdv9V47yYzQT8LWwgicwVeWGerE/exec).

Però prima di lanciare tutto, vorrei un po' fare qualche test. Ci aggiorniamo tra un po', work in progress

**Comment by salvob84** [comment]
Grazie mille Andrea

**Comment by aborruso** [comment]
Ciao @salvob84 mi sembra che funzioni tutto.

Ho pure creato un feed RSS da usare solo per Telegram, con la corretta codifica degli URL:

[https://script.google.com/macros/s/AKfycbxD44yMItkHh5EXXv4rXVLBJYT499loC1iPBWitHh8EDp9ZyA8/exec](https://script.google.com/macros/s/AKfycbxD44yMItkHh5EXXv4rXVLBJYT499loC1iPBWitHh8EDp9ZyA8/exec)

Dovresti creare un channel su Telegram dal nome AlboPretorioBarcellonaPozzodiGotto (o qualcosa di simile). Una volta fatto fammi un cenno e procediamo

**Comment by salvob84** [comment]
Scusami Andrea ero fuori per il WE.
Ho creato il canale su telegram albopopbarcellonapg

per quanto riguarda twitter/fb possiamo procedere con lo stesso script?

Grazie ancora

**Comment by aborruso** [comment]
ciao @salvob84 ci sarebbe da creare un bot e aggiungerlo come utente amministratore del canale. Qui vedi come fare [https://github.com/aborruso/albo-pop/wiki/IFTTT](https://github.com/aborruso/albo-pop/wiki/IFTTT).

Se hai difficoltà, se ti sembra incomprensibile, fai un fischio.

**Comment by salvob84** [comment]
Ciao @aborruso, ho seguito tutti i passaggi.
ho creato il bot e aggiunto come amministratore (il link del feed rss che ho usato è quello che hai postato su).
adesso per provare il funzionamento dobbiamo attendere che pubblichino qualcosa sull'albo, giusto?

**Comment by aborruso** [comment]
Sì @salvob84 , c'è da aspettare :)

**Comment by salvob84** [comment]
thanks @aborruso :)

**Comment by salvob84** [comment]
@aborruso funziona! :) grazie!

**Comment by aborruso** [comment]
Ottimo!

Inserito in elenco [http://albopop.it/comune/](http://albopop.it/comune/)
