### ISSUE TITLE
URL alboPOP Giovinazzo

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#138]
Ciao @sputnik63 ,
in #134 ci hai scritto di non riuscire ad accedere direttamente al link del singolo documento. Mi sono fatto un giro su quello di Giovinazzo e mi sembra si possa fare.

Ho inserito rapidamente in [questo foglio](https://docs.google.com/spreadsheets/d/1PsaIj7qJU1knS8qnwwe_agX94VwfylqTTee91i-RK2M/edit?usp=sharing) un esempio di come estrarre gli URL.

Che ne pensi?

**Comment by sputnik63** [comment]
Si, corretto. Me ne ero accorto anche io ma non avevo avuto modo di aggiornare il ticket qui.
Lo prendo in carico

**Comment by aborruso** [comment]
@sputnik63 se serve una mano su questa cosa, posso provare a dare una mano

**Comment by sputnik63** [comment]
Non ho avuto tempo di attivarmi. Lo farò senz'altro in questo weekend
Il 23/apr/2016 11:36, "Andrea Borruso" notifications@github.com ha
scritto:

**Comment by sputnik63** [comment]
Ok albo aggiornato
