### ISSUE TITLE
Albo POP Viadana (MN)

### ISSUE THREAD

**Issue by simoneversienti** [aborruso/albo-pop#139]
@aborruso Questo è un albo che ho particolarmente a cuore...ho conosciuto da poco una signora di Viadana e volevo che anche il loro paese avesse un albo POP.

Link: http://93.91.129.100/hypersicportal/portale/albopretorio/albopretorioconsultazione.aspx?CATEGORIA_ID=5&EVENTO_ID=1

**Comment by simoneversienti** [comment]
@piersoft

**Comment by aborruso** [comment]
@simoneversienti ho fatto un primo rapido giro, ed è di quegli albi per cui non sembra esserci un modo diretto per accedere alla pagina di dettaglio.
Si può attivare qualcosa che aggiorna per ogni nuovo atto, ma temo non sia possibile generare URL della pagina di dettaglio. Alcuni albi POP sono stati attivati così, in modo da poter avere comunque un aggiornamento con il titolo del nuovo atto.

**Comment by simoneversienti** [comment]
Si, perfetto...
Se non si può fare altro, procediamo così.
