### ISSUE TITLE
creare guida sul come rendere standard RSS il formato data

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#14]
Negli albi pretori spesso la data è in formato "11/12/2015", mentre quella standard RSS è "Fri, 11 Dec 2015 00:00:00 GMT".

E' quindi necessario fare la conversione di formato, prima di poter usare la data di pubblicazione, come data del feed RSS.

**Comment by aborruso** [comment]
Creata una prima versione [qui](https://github.com/aborruso/albo-pop/wiki/Kimonolabs#come-modificare-la-data-di-pubblicazione-per-renderla-standard-rss)

Non chiudo ancora la issue, perché c'è da scrivere qualche nota di testo

**Comment by cirospat** [comment]
grazie per il lavoro di condivisione che stai facendo su GitHub

**Comment by aborruso** [comment]
@cirospat rischia di venirne fuori qualcosa di molto utile. Ed è una direzione verso cui andare. 

Io lo faccio solo per farvi lavorare :)

**Comment by aborruso** [comment]
La guida è qui https://github.com/aborruso/albo-pop/wiki/Kimonolabs#come-modificare-la-data-di-pubblicazione-per-renderla-standard-rss
