### ISSUE TITLE
Albo Provincia Barletta-Andria-Trani

### ISSUE THREAD

**Issue by Rinux83** [aborruso/albo-pop#144]
Sto cercando di estrapolare i dati dall'albo pretorio della provincia BAT, ma utilizzando direttamente questo link (http://www.provincia.barletta-andria-trani.it/AlboPretorio/AlboPretorio.aspx) per l'import nei googlesheet la pagina restituisce un errore, e l'albo comunque si riesce a raggiungere dalla home del sito della provincia, ma no se inserisco direttamente l'url.
Qualcuno saprebbe indicarmi come poter aggirare il problema?

**Comment by aborruso** [comment]
Ciao @Rinux83 ti consiglio di provare sempre ad aprire un URL anche in una sessione anonima di un browser. Tu infatti riesci a raggiungerla perché prima vai in home, viene impostato un cookie, e poi apri l'albo. Non settando il cookie, non passando dalla home, la pagina non si apre e non l'aprirà gdrive.

Ho impostato uno script che ogni dieci minuti crea una copia aggiornata di quella pagina e su cui puoi fare girare gdrive. L'URL della pagina in copia è:
[http://dev.opendatasicilia.it/albopop/bat/index.html](http://dev.opendatasicilia.it/albopop/bat/index.html)

Lo script in bash è:

``` bash
#!/bin/bash

# imposto una cartella di lavoro
cartella="/home/aborruso/progetti/albopop/Barletta-Andria-Trani"

# imposto la cartella di output esposta sul web
output="/home/public_html/albopop/bat"

# imposto cookie di sessione
curl -s -c $cartella/cookies.txt  "http://www.provincia.barletta-andria-trani.it/"  > /dev/null 2>&1

# creo una copia dell'HTML della home dell'albo
curl -b $cartella/cookies.txt 'http://www.provincia.barletta-andria-trani.it/AlboPretorio/AlboPretorio.aspx' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.22 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://www.provincia.barletta-andria-trani.it/' -H 'Connection: keep-alive' --compressed > $output/index.html
```

**Comment by Rinux83** [comment]
Grazie @aborruso, ho messo su il feed e il canale telegram:
http://feeds.feedburner.com/AlboPopProvinciaBarlettaAndriaTrani
https://telegram.me/AlboPretorioBAT

Intanto ho anche implementato albo pop per il comune di Andria:
http://feeds.feedburner.com/AlboPopComuneAndria
https://telegram.me/AlboPretorioAndria

**Comment by aborruso** [comment]
@Rinux83 quindi tengo su lo script? Come fonte usi http://dev.opendatasicilia.it/albopop/bat/index.html?

**Comment by Rinux83** [comment]
Si

**Comment by aborruso** [comment]
@Rinux83 devi applicare l'encoding dei caratteri agli URL pubblicati su Telegram. Al limite crei due feed RSS, uno "standard" e uno che mandi solo a Telegram.

Se non lo fai 

[http://www.albo.comune.andria.bt.it/web/trasparenza/albo-pretorio;jsessionid=214AD53A56EC7D39EA05A3611BFC690E?p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=downloadAllegato&p_p_cacheability=cacheLevelPage&p_p_col_id=column-1&p_p_col_count=1&_jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet_id=1166158](http://www.albo.comune.andria.bt.it/web/trasparenza/albo-pretorio;jsessionid=214AD53A56EC7D39EA05A3611BFC690E?p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=downloadAllegato&p_p_cacheability=cacheLevelPage&p_p_col_id=column-1&p_p_col_count=1&_jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet_id=1166158)

Viene troncato a

[http://www.albo.comune.andria.bt.it/web/trasparenza/albo-pretorio;jsessionid=64E27D867769096EDDD9240472C8D29A?p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet](http://www.albo.comune.andria.bt.it/web/trasparenza/albo-pretorio;jsessionid=64E27D867769096EDDD9240472C8D29A?p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet)

Con l'encoding dei caratteri "buono" per Telegram l'URL deve diventare:

[http://www.albo.comune.andria.bt.it/web/trasparenza/albo-pretorio;jsessionid=64E27D867769096EDDD9240472C8D29A?p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet%26p_p_lifecycle%3D2%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_resource_id%3DdownloadAllegato%26p_p_cacheability%3DcacheLevelPage%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet_id%3D1166158](http://www.albo.comune.andria.bt.it/web/trasparenza/albo-pretorio;jsessionid=64E27D867769096EDDD9240472C8D29A?p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet%26p_p_lifecycle%3D2%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_resource_id%3DdownloadAllegato%26p_p_cacheability%3DcacheLevelPage%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet_id%3D1166158)

![image](https://cloud.githubusercontent.com/assets/30607/14826324/a8e1159e-0bdd-11e6-953a-5288d3c46567.png)

**Comment by Rinux83** [comment]
Ho applicato un encoding direttamente sul gsheet e per ora sembra andar bene, il link non viene troncato

**Comment by aborruso** [comment]
@Rinux83 ma lo hai cambiato? Perché quando te l'ho segnalato erano tutti troncati

**Comment by Rinux83** [comment]
si, l'ho cambiato modificando gli url ed eliminando dal canale telegram i vecchi post

**Comment by aborruso** [comment]
Allora chiudo l'issue.

Contento di essere stato utile
