### ISSUE TITLE
Albo POP Pisa Non disponibile

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#145]
Alla seguente url http://opendata.matteofortini.it/rssAlboPOP/alboPOPPisa.xml ho il messaggio 503 Service Temporarily Unavailable

**Comment by jenkin** [comment]
Sembrerebbe risolto, un messaggio su twitter fa miracoli a volte: https://twitter.com/jenkin27/status/750789795471880192 :)
