### ISSUE TITLE
creare guida su come usare gdrive per estrarre dati da una pagina web

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#15]

**Comment by aborruso** [comment]
Una prima [bozza imcompleta](https://github.com/aborruso/albo-pop/wiki/Utilizzare-Google-Drive-Sheet-per-estrarre-dati-da-una-pagina-web)

**Comment by grimaldi1972** [comment]
Avevo iniziato la sera stessa a provare Kimono, ma forse ho scelto un albo un po particolare, per non dire ermetico
https://web.spaggiari.eu/sdg/app/default/albo_pretorio.php?sede_codice=paii0001&referer=http://www.majoranapa.gov.it
Come si gestiscono i DIV? Aspettiamo di prendere confidenza per andare più affondo, mi sono risposto da solo. ;-)
Riparto da google drive: base di partenza:
https://support.google.com/docs/table/25273?hl=it&ref_topic=3105411

**Comment by aborruso** [comment]
@grimaldi1972 si fa e pure bene. Qui un RSS di prova https://www.kimonolabs.com/api/rss/bvxpidb8?&apikey=63db254e3e61d6391b87fbd9c7a33ae0&kimmodify=1

Se apri un nuovo issue ti rispondo lì con micro tutorial :)

**Comment by aborruso** [comment]
@giuragu84 ha fatto qualcosa di simile con le circolari di una scuola.

@grimaldi1972 ci vogliamo riprovare insieme?
