### ISSUE TITLE
Gestione albo pop principiante

### ISSUE THREAD

**Issue by grimaldi1972** [aborruso/albo-pop#16]
@aborruso sono in attesa istruzioni.
Non ho chiara la relazione tra ente e noi. Sul loro sito non compare niente di tutto ciò, quali sono gli accordi con l'ente. Loro aderiscono, noi prepariamo l'ambiente e poi pubblicizzano alla cittadinanza?
Il Canale su telegram/account twitter lo apre il resp albo dell'ente ?
Mi piacerebbe estendere l'albopop alle scuole.
L'esplosione dovrebbe essere più facile, non abbiamo 8000 diversi albi come i Comuni, ma nelle scuole dipende dal fornitore, fatta una fatte n.
Ho visto rss, magia. Sono andato dentro il codice ma non ho trovato le corrispondenze, figlio di figlio di figlio e nn ci ho capito niente.

**Comment by aborruso** [comment]
@grimaldi1972 ho girato un video e per oggi di più non posso fare. 

Il punto di partenza è questo albo https://web.spaggiari.eu/sdg/app/default/albo_pretorio.php?sede_codice=paii0001&referer=http://www.majoranapa.gov.it

Alcune note:
- nel codice non c'è l'href al documento, ma trovi un sospetto "id_doc"

![2015-12-14_19h29_39](https://cloud.githubusercontent.com/assets/30607/11789873/1e18a272-a299-11e5-8599-b44900a9b3cd.png)
- l'URL infatti per aprire il PDF è (nota bene c'è un **id_documento**) https://web.spaggiari.eu/sdg/app/default/view_documento.php?a=akVIEW_FROM_ID&id_documento=1856332&sede_codice=paii0001

Per generare allora questo RSS ho dovuto modificare il risultato e creare "a mano" l'URL del PDF. Un po' come ho fatto [qui](https://github.com/aborruso/albo-pop/wiki/Kimonolabs#come-modificare-la-data-di-pubblicazione-per-renderla-standard-rss), dove invece ho dovuto modificare le date.

La funzione è quella di sotto e adesso non riesco a commentarla e ti lascio al video.

``` javascript
for(var key in data.results.collection1){
    var oldData = data.results.collection1[key].pubDate;
    var arr = oldData.split('/');
    var newData = arr[2]+'-'+arr[1]+'-'+arr[0];
    var nuovadata = ((new Date(newData)).toUTCString());
    data.results.collection1[key].pubDate = nuovadata;

    var newtitle = {
    "href": "https://web.spaggiari.eu/sdg/app/default/view_documento.php?a=akVIEW_FROM_ID&sede_codice=paii0001&id_documento="+data.results.collection1[key].href.id_doc,
    "text": data.results.collection1[key].title 
    }
    data.results.collection1[key].title = newtitle;
  }
```

Il **video** lo trovi qui: https://goo.gl/AlTXmu

Fammi sapere se è comprensibile.

**Comment by giuragu** [comment]
@grimaldi1972 per quanto riguarda come agire per adesso ci sono due diverse esperienze. Bagheria si sviluppa con un funzionario "avanti" che riesce a coinvolgere amministrazione e quindi parte tutto e contemporaneamente parte il comunicato stampa di "condivisione" da parte del comune. L'altra esperienza è San Giuseppe Jato in cui sono direttamente interessato come sai. Qui ho fatto presente tutto all'amministrazione prima di partire...ne ho quindi richiesto la condivisione ufficiale. Nonostante gli apprezzamenti non si è potuto ufficializzare ancora una condivisione per motivi a quanto pare burocratici. Quindi siccome l'innovazione a volte non può attendere siamo partiti comunque. Naturalmente si spera che dall'amministrazione possa arrivare prima o poi la condivisione ufficiale.
@aborruso ho detto bene? :)

**Comment by aborruso** [comment]
@grimaldi1972 eccoti due feed RSS:
- quello ufficiale [http://feeds.feedburner.com/AlboMajoranaPalermo](http://feeds.feedburner.com/AlboMajoranaPalermo)
- quello da usare per il canale Telegram [http://blog.spaziogis.it/static/ods/data/albopop/scuole/majorana/feed_telegram.xml](http://blog.spaziogis.it/static/ods/data/albopop/scuole/majorana/feed_telegram.xml)

Il modello si replica in pochissimo tempo per tutte le altre scuole

**Comment by aborruso** [comment]
@grimaldi1972 quì il foglio elettronico usato per estrarre i dati [https://docs.google.com/spreadsheets/d/1Ae-zu3UQizDGKHhq_lSYgBR61PwVHSPP-80idXIk4zM/edit#gid=0](https://docs.google.com/spreadsheets/d/1Ae-zu3UQizDGKHhq_lSYgBR61PwVHSPP-80idXIk4zM/edit#gid=0)

**Comment by aborruso** [comment]
@grimaldi1972 per realizzarlo ho usato uno script in bash (come [questo](https://github.com/aborruso/albo-pop/blob/master/code/webpage2rss.sh))

Ma lo puoi fare anche con kimono. Devi catturare l'id_doc e poi ricostruire con le funzioni di modify di kimono l'URL.

![2016-02-10 08h11_16](https://cloud.githubusercontent.com/assets/30607/12940980/656fdb38-cfce-11e5-93ea-0b1b2d2c2e27.gif)
