### ISSUE TITLE
Hackspace e AlboPOP ad etnacomics

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#160]
Ciao, quest'anno nello stand di Hackspace Catania terrò un piccolo spazio e pensavo di dedicarlo ad albo POP (come sapete abbiamo una campagna di finanziamento riguardante l'implementazioni di Albo POP). Esporremo alcune vignette riguardanti l'utilizzo di albo pop e aiuteremo la gente a installarlo sul cellulare.

Il problema è la comunicazione. Oltre alle vignette, pensavo inizialmente di fare un banner Albo POP, col logo a 4 colori e così via. Mi sono reso conto però che facendo così sembra che il progetto Albo POP sia un progetto di Hackspace Catania quando non è così.

Suggerimenti?

**Comment by cristianolongo** [comment]
Il volantino che sto usando è disponibile qui

http://www.opendatahacklab.org/site/events/etnacomics2016/installaPOP.pdf

Non c'e' alcun riferimento ad Hackspace

**Comment by aborruso** [comment]
@cristianolongo grazie per averci avvisato e per quanto fatto.

Io per ora sono un po' affogato, ma su questo e altri temi dobbiamo fare una riunione.

Oggi provo a fare una proposta.
