### ISSUE TITLE
alboPOP Messina: aggiungere noindex nel feed RSS

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#169]
Per mettere una "pezza" nel (finto a mio avviso) problema legale dell'indicizzazione degli albi, aggiungerei nella testa del feed RSS la seguente stringa.

```
<xhtml:meta xmlns:xhtml="http://www.w3.org/1999/xhtml" name="robots" content="noindex" />
```

**Comment by gpirrotta** [comment]
La libreria che uso per generare il feed (Zend Feed) "sembrerebbe" non gestire la possibilità di inserire "meta". Devo verificare meglio.
