### ISSUE TITLE
Aggiungere Campobello di Licata

### ISSUE THREAD

**Issue by matteoscire** [aborruso/albo-pop#17]
Il sito del Comune di Campobello di Licata rilascia già il feed rss dell'albo pretorio. Tuttavia il feed va corretto e pertanto ho deciso di estrarlo con gdrive.
- Primo problema: sono riuscito ad estrarre titolo e data, ma non il link. L'Xpath che ho utilizzato è questa: //tbody/tr/td[4]/a.
  Ecco di seguito l'html della pagina.
  ![image](https://cloud.githubusercontent.com/assets/16288523/11814091/50f22c02-a345-11e5-9448-1f8502e76eeb.png)
  Dove sbaglio?

**Comment by matteoscire** [comment]
Secondo problema: le pagine dell'albo pretorio hanno tutte lo stesso url. Come faccio a scovare il loro indirizzo univoco?

**Comment by matteoscire** [comment]
Terzo problema: come faccio a standardizzare la data con gdrive?

**Comment by aborruso** [comment]
@matteoscire che bello vederti all'opera!!!

Condividi qui in scrittura il foglio elettronico e lo usiamo come pagina di test condivisa? Dai una condivisione in edit a chiunque abbia il foglio

**Comment by matteoscire** [comment]
https://docs.google.com/spreadsheets/d/1zjTMY2YpnRmMGrGuqBrOARV91v1OjkkVHh20Qv3gQWY/edit#gid=0

**Comment by aborruso** [comment]
Per l'URL puoi usare `//tbody/tr/td[4]/a/@href` che scende più in profondità e estrae la proprietà href.

A quel punto non ti resta che concatenare l'estrazione ottenuta con la prima parte dell'URL "http://www.comune.campobellodilicata.ag.it"

**Comment by giuragu** [comment]
@matteoscire inserisco qui il link all'albo pretorio non pop. Penso possa essere utile a tutti:
http://www.comune.campobellodilicata.ag.it/?q=albo-pretorio

**Comment by matteoscire** [comment]
La concatenazione va fatta cella per cella o esiste un'unica formula che concatena l'url http://www.comune.campobellodilicata.ag.it a tutte le celle della colonna Url?

**Comment by aborruso** [comment]
Basta fare copia e incolla della formula dalla prima riga della colonna link a tutte le altre. Se apri il [foglio](https://docs.google.com/spreadsheets/d/1zjTMY2YpnRmMGrGuqBrOARV91v1OjkkVHh20Qv3gQWY/edit#gid=0) lo vedi.

**Comment by matteoscire** [comment]
Ok. Passiamo al secondo problema: le pagine dell'albo pretorio hanno tutte lo stesso url. Come faccio a scovare il loro indirizzo univoco?

**Comment by giuragu** [comment]
@matteoscire @aborruso provo a contribuire...per ottenere le pagine successive credo basta inserire in coda "?page=n". Quindi ad esempio con http://www.comune.campobellodilicata.ag.it/albo-pretorio?page=1 si ottiene la seconda pagina e così via....

Ci sono arrivato ispezionando l'elemento qui:
![immagine](https://cloud.githubusercontent.com/assets/12112056/11836479/4a1cdf4e-a3db-11e5-91f3-2b68cdac85e4.png)

**Comment by matteoscire** [comment]
@giuragu84 perfetto!

**Comment by matteoscire** [comment]
Basta fermarsi alla seconda pagina dell'albo pretorio perchè in ognuna vengono pubblicati 20 avvisi. Adesso devo standardizzare la data. Come si fa?

**Comment by aborruso** [comment]
Ciao Matteo inizio dal dirti che un formato corretto è questo:

`Sat, 07 Sep 2002 0:00:01 GMT`

Altre possibilità sono quelle che leggi [qui](https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html).

Devi provare a sperimentare le stringhe di estrazione di testo del foglio elettronico e ricomporre il tutto a partire dai dati originali.

Come ora, se non fosse presente in origine, puoi usare 0:00:00.

**Comment by matteoscire** [comment]
Ciao Andrea,
il sindaco mi chiede di inserire nell'AlboPOP anche i "concorsi" e le "gare", che non vengono pubblicati anch'essi nell'Albo del sito del Comune ma nelle omonime sezioni del sito.

**Comment by matteoscire** [comment]
Ho provato a fare lo scraping, ma c'è qualcosa che non va con la data.
https://docs.google.com/spreadsheets/d/1ysznM-jb8ijOI-VFN51T0NtHzYvjXnYpO52m2dAvyXI/edit#gid=0

**Comment by aborruso** [comment]
@matteoscire modificato un po' l'XPATH e usato la funzione `REGEXEXTRACT` di gdrive (https://support.google.com/docs/answer/3098244?hl=en&ref_topic=3105625) per estrarre dalla stringa "Mar, 29/12/2015 - 12:56" soltanto "29/12/2015".

Il foglio di output su cui fare lavorare kimono è questo:
https://docs.google.com/spreadsheets/d/1ysznM-jb8ijOI-VFN51T0NtHzYvjXnYpO52m2dAvyXI/edit#gid=876098420
