### ISSUE TITLE
alboPOP Patti: usare come link, l'URL del PDF

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#171]
Visto che nell'albo di Patti originale non ci sono permalink per in singoli atti, e che ogni link punta all'homepage, sostituirei l'URL attuale dei link, con l'URL del PDF allegato che pare esserci sempre.

Così tutto sarebbe molto più contestualizzato e univoco

**Comment by gpirrotta** [comment]
Fixed
