### ISSUE TITLE
Feed RSS Messina: mancando delle pubblicazioni

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#177]
@gpirrotta se guardi il [feed RSS](https://script.googleusercontent.com/macros/echo?user_content_key=cNpTVDamZfciVHCwproO1reQe0t8DR4NdgQKLKqFZPS_qATVS3y2VOLzHXgsQWjrK4mDrkvFXmeQ-vXXwSABWPpTJWJI8Za2m5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnPzWj_RMnXlj9deXao6t2yqoHkjlqeu8BuSwrV03TLZbe5v623TOaqeuI-IV2hPBNvU98RMxP90z&lib=MbH48APRCcHpsRBIwgXVOy0wBSA0_FGxs) che avevo creato io (a cui mancava ancora la parte di estrazione del titolo completo) noterai che ci sono molto più elementi di quelli presenti adesso nel tuo. 

Nel tuo dal 26 giugno al 17, non c'è nulla, mentre (a parte i matrimoni) ci sono ad esempio delibere di giunta del 23. Che ne pensi?

Non so se ti può essere utile, [qui](https://github.com/aborruso/albo-pop/blob/master/code/messina/test.sh) c'è il mio brutto script bash da cui estraggo i dati che poi uso per generare RSS.

**Comment by gpirrotta** [comment]
Fixed
