### ISSUE TITLE
Come connetto su IFTTT l'Rss a Telegram?

### ISSUE THREAD

**Issue by matteoscire** [aborruso/albo-pop#18]

**Comment by matteoscire** [comment]
Su Ifttt vado in My Recipes, quindi "IfThis", seleziono l'rss, lo inserisco. Quando poi vado su "ThenThat" non capisco quale applicazione scegliere. Ho provato con Maker, ma penso non sia quella giusta.
Aiuto.

**Comment by aborruso** [comment]
@matteoscire non me lo sono dimenticato, giurò che scrivo una guida nei prossimi giorni :) (forse stanotte)

**Comment by aborruso** [comment]
Ecco la prima versione della guida:

https://github.com/aborruso/albo-pop/wiki/IFTTT#pubblicare-gli-aggiornamenti-di-un-feed-rss-su-un-canale-telegram

E' un wiki, quindi tutti noi possiamo integrare, correggere e migiorare

**Comment by cirospat** [comment]
aggiornata la wiki dei tutorial ;-)
https://github.com/cirospat/tutorial-open-data/wiki/Tutorial-per-open-data

Il giorno 20 dicembre 2015 09:13, Andrea Borruso notifications@github.com
ha scritto:
