### ISSUE TITLE
Dati mappa non caricati

### ISSUE THREAD

**Issue by jenkin** [aborruso/albo-pop#184]
Mi sa che c'è un problema nell'accesso al [foglio di calcolo condiviso](http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD&key=1a-XlQl6jHxsHuemPEMLCEz9qekFnLr_-bfqnhBOwdvc&gid=1311822177). Il link diretto funziona, ma ritorna un errore in json, invece che un csv: `{"version":"0.6","status":"error","errors":[{"reason":"invalid_query","message":"INVALID_QUERY","detailed_message":"Invalid query: NO_COLUMN: B"}]}`.

**Comment by aborruso** [comment]
Risolto, grazie.

Usavo delle API che adesso non sono più free. Solved con Nominatim
