### ISSUE TITLE
Come standardizzare la data su Gdrive?

### ISSUE THREAD

**Issue by matteoscire** [aborruso/albo-pop#19]

**Comment by aborruso** [comment]
Ciao Matteo inizio dal dirti che un formato corretto è questo:

`Sat, 07 Sep 2002 0:00:01 GMT`

Altre possibilità sono quelle che leggi [qui](https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html).

Devi provare a sperimentare le funzioni di estrazione di testo del foglio elettronico e ricomporre il tutto a partire dai dati originali.

Come ora, se non fosse presente in origine, puoi usare 0:00:00.

**Comment by aborruso** [comment]
Se da gdrive passi poi per kimono, puoi usare [questa modalità](https://github.com/aborruso/albo-pop/wiki/Kimonolabs).

**Comment by aborruso** [comment]
@matteoscire ma l'hai letta la pagina a cui faccio riferimento [qui](https://github.com/aborruso/albo-pop/issues/19#issuecomment-168226688)?  Te lo chiedo perché nel codice che mi hai inviato non c'è traccia del codice che trovi scritto lì. 
Fammi sapere
