### ISSUE TITLE
Sostegno ad openamat negli annunci condivisi

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#197]
Aggiungere nelle pagine di condivisione degli avvisi degli albi pretori un banner di supporto a open amat

> Albo POP XXX sostiene l'iniziativa <a href="https://www.facebook.com/groups/271334679900477">#openamat</a>
>     per la liberazione dei dati sul trasporto pubblico a Palermo.

**Comment by aborruso** [comment]
Bell'idea

**Comment by riccardomariagrosso** [comment]
Concordo
Il 14/lug/2016 19:29, "Andrea Borruso" notifications@github.com ha
scritto:

**Comment by cristianolongo** [comment]
Catania fatto

**Comment by cristianolongo** [comment]
unict e unito fatte

**Comment by cristianolongo** [comment]
torino

**Comment by riccardomariagrosso** [comment]
unito e comuneto ai prossimi giri di nuovi feed avranno il banner amat,
giusto ?

2016-07-14 21:01 GMT+02:00 Cristiano Longo notifications@github.com:

> torino
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/aborruso/albo-pop/issues/197#issuecomment-232760652,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACVKtBCipP75Kyl9MISXhM8Rfk4j2CQfks5qVoeWgaJpZM4JMqIz
> .

## 

http://nelfuturo.com/autore/Riccardo-Grosso

Questo è un account di posta personale di Riccardo Maria Grosso: tutte le
opinioni espresse sono personali e non riflettono necessariamente quelle
del mio datore di lavoro

Riservatezza: In ottemperanza al D.Lgs. n. 196 del 30/6/2003 in materia di
protezione dei dati personali, le informazioni contenute in questo
messaggio sono strettamente riservate ed esclusivamente indirizzate al
destinatario indicato (oppure alla persona responsabile di rimetterlo al
destinatario). Vogliate tener presente che qualsiasi uso, riproduzione o
divulgazione di questo messaggio è vietato. Nel caso in cui aveste ricevuto
questo messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.
Rispetto per l'ambiente - non stampare questa e.mail se davvero non ne hai

## bisogno

Confidentiality: According to Italian law D.Lgs. 196/2003 concerning
privacy, if you are not the addressee (or responsible for delivery of the
message to such person) you are hereby notified that any disclosure,
reproduction, distribution or other dissemination or use of this
communication is strictly prohibited. If you have received this message in
error, please destroy it and notify us by email.
Consider the environment - do not print this email if you really do not
need to do so

**Comment by cristianolongo** [comment]
sono già li ;)

**Comment by riccardomariagrosso** [comment]
visto ! perfetto

2016-07-14 21:05 GMT+02:00 Cristiano Longo notifications@github.com:

> sono già li ;)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/aborruso/albo-pop/issues/197#issuecomment-232761723,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACVKtACypcA_Bae_MnIlodBuvaFbFyaTks5qVoiAgaJpZM4JMqIz
> .

## 

http://nelfuturo.com/autore/Riccardo-Grosso

Questo è un account di posta personale di Riccardo Maria Grosso: tutte le
opinioni espresse sono personali e non riflettono necessariamente quelle
del mio datore di lavoro

Riservatezza: In ottemperanza al D.Lgs. n. 196 del 30/6/2003 in materia di
protezione dei dati personali, le informazioni contenute in questo
messaggio sono strettamente riservate ed esclusivamente indirizzate al
destinatario indicato (oppure alla persona responsabile di rimetterlo al
destinatario). Vogliate tener presente che qualsiasi uso, riproduzione o
divulgazione di questo messaggio è vietato. Nel caso in cui aveste ricevuto
questo messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.
Rispetto per l'ambiente - non stampare questa e.mail se davvero non ne hai

## bisogno

Confidentiality: According to Italian law D.Lgs. 196/2003 concerning
privacy, if you are not the addressee (or responsible for delivery of the
message to such person) you are hereby notified that any disclosure,
reproduction, distribution or other dissemination or use of this
communication is strictly prohibited. If you have received this message in
error, please destroy it and notify us by email.
Consider the environment - do not print this email if you really do not
need to do so
