### ISSUE TITLE
Aggiungere Isola delle Femmine

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#2]
Feed Rss http://feeds.feedburner.com/AlboPretorioIsolaDelleFemmine

**Comment by grimaldi1972** [comment]
Vedi
https://github.com/aborruso/albo-pop/issues/36

**Comment by joska1978** [comment]
ciao mario! 
 ho parlato l'altro ieri con la dipendente del comune di isola delle femmine che si occupa della gestione dell'albo pretorio on line (cinzia cardinale). 
 si è dimostrata disponibile in caso a verificare le problematiche inerenti l'albo per vedere come si deve agire e quali criticità sono presenti e come superarle.  per quanto riguarda l'amministrazione comunale di isola (a livello assessori della giunta) le condizioni poi per discutere con calma dell'implementazione dell'albo pop si possono creare, una volta risolte queste problematiche tecniche.

i rapporti di questi tempi sono costanti e positivi per poter creare le condizioni.

se vuoi organizziamo l'incontro con cinzia cardinale e vediamo insieme il da farsi.

che dici?
