### ISSUE TITLE
Albo POP Caprarica di Lecce

### ISSUE THREAD

**Issue by simoneversienti** [aborruso/albo-pop#204]
Il caro amico Domenico Aprile ha bisogno di noi...
Questo è il link dell'albo: [http://www.svichosting.com/caprarica/mc/mc_gridev_messi.php?x=&servizio=&bck=http%3A%2F%2Fwww.comune.caprarica.le.it%2F]
@piersoft possiamo dare una mano?

**Comment by piersoft** [comment]
ora vedo

2016-07-26 13:07 GMT+02:00 simoneversienti notifications@github.com:

**Comment by piersoft** [comment]
ci vorrebbe un automa che faccia lo scraping. infatti in quel link non hai
la tabella ma hai una chiamata a
http://www.svichosting.com/caprarica/mc/mc_gridev_messi_datigrid.php?x=1451606400

mi spiace.

Il giorno 26 luglio 2016 15:54, Francesco Piero Paolicelli <
piersoft2@gmail.com> ha scritto:

**Comment by aborruso** [comment]
Ciao @simoneversienti ecco il feed RSS: http://feeds.feedburner.com/AlboCapraricaDiLecce

Ovviamente come al solito è bene fare un po' di test e verifiche. Fatemi sapere
