### ISSUE TITLE
Generalizzazione albi JCityGov

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#208]
L'albo del comune di Belpasso è un albo realizzato con piattaforma jCityGov. Estrarre il codice che può essere generalizzato dal parser dell'albo di Belpasso e creare una classe apposita nella cartella jCityGov. Aggiornare il parser dell'albo pop di belpasso.

**Comment by patperu** [comment]
Ciao Cristiano, 
some months ago I wrote a R package for Albo Pop and one of the sites the parser works with is `JCitygov`. These are the relevant lines https://github.com/patperu/albopop/blob/master/R/ap_parse_page.R#L62 Here you find the current feeds: http://www.covimo.de/albo_pop/ I have just added Belpasso

**Comment by cristianolongo** [comment]
Thank you very much pat, I'm just generalizing some code I wrote for the albo of belpasso, which is a jCityGov one (i think). Now let us see if it works for another jCityGov ablbo I found.

**Comment by cristianolongo** [comment]
2619ac395a1295d53b9bdaf73457d038608b9859
