### ISSUE TITLE
Specifiche per una struttura condivisa dei feed RSS prodotti

### ISSUE THREAD

**Issue by jenkin** [aborruso/albo-pop#214]
Nell'ottica di aggregare i vari feed prodotti dagli scraper credo sia utile e necessario fissare delle specifiche sul formato di questi feed, in modo tale che tendenzialmente tutti vi si adeguino.

Non credo sia necessario [estendere il formato RSS](https://cyber.harvard.edu/rss/rss.html#extendingRss) e arrivare alla definizione di tag personalizzati mediante un namespace `albopop:`, basta indicare delle buone prassi per un uso corretto e condiviso del formato RSS.

Provo a sviluppare una bozza di pagina di specifiche in una [branch a parte](https://github.com/jenkin/albo-pop/blob/albopop-specs/specs.md), sintetizzando le riflessioni emerse in [questa issue](https://github.com/ondata/albopop-enhanced/issues/7) e in https://github.com/aborruso/albo-pop/issues/187, https://github.com/aborruso/albo-pop/issues/186 e https://github.com/aborruso/albo-pop/issues/185.

**Comment by jenkin** [comment]
Ecco [qua](https://github.com/jenkin/albo-pop/blob/albopop-specs/specs.md), attendo feedback prima di procedere con una pull request... :)

**Comment by gpirrotta** [comment]
Mi piace molto l'idea di adottare delle specifiche interne per avere un unico vocabolario condiviso atto a definire un dominio di riferimento specifico.
Alle specifiche che proponi ne aggiungerei anche altre per definire il contesto di ogni singolo item, informazione spesso presente anche nella pagina **elenco atti** oltre che in quella **dettaglio atto**.
Alcune informazioni di contesto sono modellabili con lo schema che proponi, per altre potrebbero essere definite nuove **category**.
Ti elenco altre informazioni di ogni singolo item che si _dovrebbero_ rappresentare in qualche modo.
- tipologia (delibera, determinazione, pubblicazioni matrimonio, etc)
- numero atto settore
- data fine pubblicazione 
- data emissione
- data inizio esecuzione
- unità organizzativa responsabile (es. Area Servizi Demografici)
- oggetto o titolo (**description**)
- descrizione
- stato  (scaduto, in vigore)
- forma (integrale, parziale)
- importo
- capitolo
- annotazioni

Ovviamente non tutti i punti sono obbligatori nè presenti in tutti gli albi.  Per le date userei **ISO 8601**.
my2c

**Comment by aborruso** [comment]
Metto anche qui il primo albo con specifiche Cimarellix http://feeds.feedburner.com/AmatriceCimarellix

**Comment by jenkin** [comment]
@gpirrotta sarebbe bello avere tutto il più strutturato possibile... non vorrei però rendere il tutto anche troppo complicato... che ne dite se mettiamo tutto, ma identifichiamo anche un sotto insieme minimo di contenuti strutturati? Poi nella pagina proviamo a diversificare graficamente i vari elementi... :)

**Comment by jenkin** [comment]
Hmm, c'è tra l'altro un piccolo problema: le category all'interno dell'item si possono riferire all'item stesso, ma anche al suo feed originale (cioè alla fonte). Bisognerebbe differenziarle...

**Comment by aborruso** [comment]
@jenkin non voglio modificare il tuo schema, voglio solo ragionare.

Non sarebbe meglio inserire a livello di channel ciò che è proprio del channel (e quindi condiviso con i figli, gli item) e a livello di item inserire solo ciò che è proprio del singolo item.

Quindi ad esempio nel channel cose come:

```
<category domain="http://albopop.it/specs#item-category-region">Lazio</category>
```

E nell'item solo cose come:

```
<category domain="http://albopop.it/specs#item-category-act">[...]</category>
```

Secondo me dovrebbe essere il motore che consuma l'RSS ad associare automaticamente "Regione Lazio" a tutti gli item in cui nel channel padre c'è scritto "Regione Lazio".

**Comment by jenkin** [comment]
@aborruso è la scelta più logica, ma temo per esempio che ttrss non funzioni così... conosci aggregatori (tanti feed in ingresso, un solo feed in uscita) che faccia questo giochino out-of-the-box?

**Comment by aborruso** [comment]
@jenkin io penso al vostro bel  motore, e a costruire questo per AlboPOP enhanced è lui che deve trovarne giovamento.

Del resto, per feed veri come [questo](view-source:https://en.blog.wordpress.com/feed/), in cui ci sono le categorie per i vari item, sono io che mi andrò a costruire un modo per filtrarli/mescolarli/aumentarli.
E' un XML con il suo comodo schema.

Qui si sta costruendo un motore intelligente che consuma RSS e proponevo una modifica alla modalità di "consumazione".

So che ci vuole tempo. Detto questo, possiamo implementare da subito una versione ridondante e aprire una feature request per il futuro.

Però decidi tu. Dimmi con calma cosa c'è che non va in [questo primo output](http://feeds.feedburner.com/AmatriceCimarellix) costruito con il nuovo schema.

**Comment by jenkin** [comment]
@aborruso quello che hai fatto va benissimo, cerco di ragionare su come rendere albopop migliore in termini generali, indipendentemente dai limiti di ap enhanced... 😄 

Questione numero 1: dentro ES, che è un nosql document-based, tutte le informazioni relative a un item (e quindi anche quelle del channel a cui appartiene) _devono_ essere dentro l'item.

Questione numero 2: al momento logstash indicizza il feed aggregato in ES, non posso inserire in logstash i singoli feed (da cui potrei prendere le category del channel), perché non scala, sono troppi... ho bisogno di un aggregatore che aggiorni i singoli feed in un processo indipendente, ne mantenga una cache abbastanza lunga (tipo un giorno) ed esporti un singolo feed aggregato.

Esiste una roba basica che lo faccia? Al momento usiamo ttrss, che volendo si può _ritoccare_ affinché gestisca come vogliamo le category a livello di channel (associandole anche agli item). Non mi piace l'idea di una soluzione ridondante... :)

**Comment by jenkin** [comment]
Ok, dai, ho capito cosa e come modificare in ttrss, definiamo i tag category sia a livello di channel che di item... domani penso di riuscire ad aggiornare le specs... :)

**Comment by gpirrotta** [comment]
@jenkin ok. Inoltre non tutti gli attributi saranno sempre presenti per ogni item e non tutti sono obbligatori. Bisognerebbe definire nello schema quelli **REQUIRED** da quelli no. Il periodo di validità, inizio e fine ad esempio lo metterei tra i **REQUIRED**, l'ufficio proponente invece no e così via.

**Comment by aborruso** [comment]
@jenkin @gpirrotta dai, apriamo i lavori ufficiali sulle specifiche. Un pezzo già è fatto e il resto lo costruiamo.

Farei una cartella dedicata qui, o dove dite voi.

**Comment by gpirrotta** [comment]
@jenkin @aborruso  la definizione dello schema _dovrebbe_ essere il più possibile agnostica dall'applicazione, non è sbagliato pensare di specificare il contesto tramite **CHANNEL CATEGORY** e **ITEM CATEGORY**, imho.
Se le informazioni estratte mi servono in un certo modo, perchè il consumatore (ad. es. ES) le aspetta raggruppate, non è responsabilità dello schema far in modo che siano **application-oriented.** 

Stavo facendo delle prove. 

Con semantica più esplicita:

```
<category domain="http://albopop.it/specs#item-category-act-id">117</category>
<category domain="http://albopop.it/specs#item-category-act-type">Determinazione</category>
<category domain="http://albopop.it/specs#item-category-act-status">In vigore</category>
<category domain="http://albopop.it/specs#item-category-act-pubEnd">Wed, 14 Sep 2016 10:00:00 +000</category>
<category domain="http://albopop.it/specs#item-category-act-chapter">3</category>
<category domain="http://albopop.it/specs#item-category-act-amount">1000</category>
<category domain="http://albopop.it/specs#item-category-act-annotation"></category>
```

Più generico:

```
<category domain="http://albopop.it/specs#item-category-id">117</category>
<category domain="http://albopop.it/specs#item-category-type">Determinazione</category>
<category domain="http://albopop.it/specs#item-category-status">In vigore</category>
<category domain="http://albopop.it/specs#item-category-pubEnd">Wed, 14 Sep 2016 10:00:00 +000</category>
<category domain="http://albopop.it/specs#item-category-chapter">3</category>
<category domain="http://albopop.it/specs#item-category-amount">1000</category>
<category domain="http://albopop.it/specs#item-category-annotation"></category>
```

Quale vi suona meglio? Suggerimenti diversi?

**Comment by jenkin** [comment]
Direi che la seconda è perfetta... per l'equivalente del channel, metterei il prefisso channel- al posto di item-. Comunque sto aggiornando la mia branch, tra pochi minuti ve la condivido... :)

**Comment by jenkin** [comment]
Ecco qua, ho aggiornato il tutto: https://github.com/jenkin/albo-pop/blob/albopop-specs/specs.md.

Alcune domande...
- Lo status è una variabile? "In vigore" per esempio cambia nel tempo?
- Al momento prevediamo due licenze: una col tag _copyright_ e una con _creativeCommons:license_. Non sono in conflitto?
- Che categorie indichiamo come obbligatorie?

**Comment by gpirrotta** [comment]
1) **status** nel tempo cambia da **In vigore** a **scaduto** e dipende dall'attributo **pubEnd**.
2) Dipende dai dati di partenza, possiamo prevedere l'utilizzo di una licenza piuttosto che un'altra in modo esclusivo. 
3) Per quanto riguarda l'obbligatorietà delle categorie, un'idea (parziale) potrebbe essere:

**CHANNEL**
nazione pa,
regione pa,
provincia pa,
comune pa,
latitudine pa,
longitudine pa,
codice univoco con prefisso pa
tipo pa  **\- obbligatoria -**
nome pa **\- obbligatoria -**

**ITEM**
Le categorie in corsivo perchè non le facciamo ereditare da channel?

_nazione atto,
regione atto,
provincia atto,
comune atto,
latitudine atto,
longitudine atto_

codice univoco con prefisso atto, **\- obbligatoria -**
tipo atto, 
data di pubblicazione dell'atto, **\- obbligatoria -**
data di scadenza dell'atto, **\- obbligatoria -**
data di emissione dell'atto,
data di inizio esecuzione dell'atto,
capitolo dell'atto,
unità organizzativa responsabile dell'atto,
importo complessivo dell'atto,
valuta in cui è espresso l'importo,
annotazioni a corredo dell'atto.

Le informazioni geografiche le lascerei come opzionali (al limite nazione e regione potrebbero essere le uniche obbligatorie). Andrebbero definite anche le cardinalità delle categorie. Penso ad esempi all'albo dell'UNIMORE, Università detli Studi di Modena e Reggio Emilia, due città e due province.

La data di scadenza dell'atto è un dato obbligatorio ma purtroppo ho visto albi in cui non è sempre specificata per tutti gli item. In questo caso metterei come default 15 giorni dopo la data di pubblicazione.

Per quanto riguarda il _codice univoco con prefisso atto_ spesso i comuni accorpano insieme numero atto e anno di pubblicazione. In questo modo l'atto diventerebbe univoco all'interno dello stesso albo. 

Alcuni comuni stanno iniziando a pubblicare anche informazioni relative ai beneficiari dell'atto, ai suoi dati fiscali e soprattutto al responsabile del procedimento amministrativo.

Esempio di schema: 

### Nome beneficiario

```
<category domain="http://albopop.it/specs#item-category-beneficiary-name">Mario Rossi</category>
```

### Altre info beneficiario

```
<category domain="http://albopop.it/specs#item-category-beneficiary-other">RSSMRA75L01H501P</category>
```

### Responsabile del procedimento amministrativo

```
<category domain="http://albopop.it/specs#item-category-process-owner">Paolo Verdi</category>
```

**Comment by jenkin** [comment]
@gpirrotta sempre più complicato... :)
- eliminerei allora la categoria status (calcolabile univocamente);
- metterei "Copyright [anno] [nome pa]"
- ok obbligatorietà categorie channel;
- info geografiche dell'item, per il momento forse hai ragione, anche se in teoria il singolo atto potrebbe averne di sue specifiche (pensa al lavoro di sistemazione di un incrocio stradale, per esempio);
- ok obbligatorietà categorie item;
- non ci sono problemi per la cardinalità, puoi mettere quante category vuoi con lo stesso domain, poi è il client che le deve gestire;
- non sono sicuro per i valori di default: li mette lo scraper o lo lasciamo al client? io sono per la seconda ipotesi;
- il codice univoco dell'atto secondo me è il codice di protocollo, ovviamente valido solo all'interno di quell'albo;
- beneficiari e responsabili: li possiamo aggiungere...

**Comment by gpirrotta** [comment]
- ok per la rimozione della categoria status, si può calcolare da **pubEnd**
- il valore di default di **pubEnd**, quando non è specificato, può essere valorizzato sia dal client che dallo scraper. Toglierei quindi l'obbligatorietà a **pubEnd** lasciando la responsabilità (a loro discrezione) ai produttori/consumatori dell'RSS.
- un'osservazione: il numero dell'atto pubblicato nell'albo pretorio non è il numero del protocollo. Il primo è una sequenza incrementale dedicata e nel documentale di una PA solitamente è un repertorio a sè.
  Il numero del protocollo è invece una sequenza globale annua incrementale che coinvolge **tutti** i documenti in arrivo, in partenza e tra uffici. Solitamente un atto pubblicato ha un numero di protocollo (unico per la PA e identificato nella stampigliatura del PDF) e un numero di repertorio, che è il numero dell'albo pretorio. Io direi di mettere in **uid**, ad esempio, **2016/7316**.
  Inoltre, anche se è forse eccessivo, potrebbe avere senso una categoria (opzionale) a sè e svincolare l'anno da uid.

```
<category domain="http://albopop.it/specs#item-category-pubYear">2016</category>
```

Cosa ne pensate?

**Comment by jenkin** [comment]
Aspetta, l'uid che proponi è il numero di protocollo o il numero dell'atto?

**Comment by gpirrotta** [comment]
Il numero dell'atto, con anteposto l'anno di pubblicazione.

**Comment by jenkin** [comment]
Ok, ho aggiornato le specifiche... direi che ci siamo...

**Comment by jenkin** [comment]
Ok, ora le nuove specifiche sono pubblicate ufficialmente su albopop: http://albopop.it/specs/. Chiudo questa issue, eventuali commenti / modifiche andranno in issue separate... grazie a tutti!
