### ISSUE TITLE
lentezza nel generare il feed

### ISSUE THREAD

**Issue by pietrondo** [aborruso/albo-pop#215]
Buongiorno stiamo provando RSSGen.gs
ma è da qualche giorno che il "tempo" per generare il feed è diventato lungo e i vari software online (feedburner ad esempio) non ce lo permettono di leggere come rss.
Abbiamo visto che i tempi di esecuzione dello script (che comunque funziona su macchine locali) sono molto lunghi, generando cosi timeout.
Grazie

**Comment by aborruso** [comment]
@pietrondo lo usiamo in decine di casi, senza problemi. Se lo usi a partire da uno spreadsheet e lo puoi condividere, posso provare a fare un check.

Grazie a te

**Comment by pietrondo** [comment]
ora sembra risolto... però ho scoperto un nuovo "problema" (lo posto qua o in nuovo issue?)
il formato data, nel rss finale esce cosi:       <pubDate>Thu, 01 Jan 1970 00:00:00 +0000</pubDate>

su tutti i feed nuovi

**Comment by aborruso** [comment]
Pietro se condividi il foglio, posso aiutarti con la data :)

Il sab 17 set 2016 02:31 Pietro notifications@github.com ha scritto:

**Comment by pietrondo** [comment]
Ciao, scusami se ti rompo, ma ieri sera avevo voglia di provare a
modificare script...
per risolvere ho modificato lo script sulla data cosi:

 var pDateFix=new Date(pDate );

```
var pubDateDate = pDateFix;
```

//                Logger.log(pubDateDate);

(logger l'ho usato per fare il debug (magari può servire ad altri) di come
compariva la data.

Praticamente il  + " 12:00" mi manda il pudDate nel 1970 
(come file ho usato: 
https://github.com/aborruso/albo-pop/blob/master/code/GDriveGeneric/RSSGen.gs )

grazie ancora per l'attenzione

**Comment by aborruso** [comment]
@pietrondo su che Albo stai lavorando? Non appena è tutto pronto invii qui i canali che hai aperto e lo mettiamo in elenco.

Grazie

**Comment by pietrondo** [comment]
ok appena abbiamo pronto ti mandiamo.
Per la lentezza dell'altro giorno l'abbiamo imputato a google (ora è tutto a posto). 
Grazie mille
