### ISSUE TITLE
Come connetto su IFTTT gdrive a Telegram?

### ISSUE THREAD

**Issue by giuragu** [aborruso/albo-pop#22]
@aborruso ho connesso il canale gdrive ma non trovo la possibilità di creare una ricetta che parta da gdrive o sheet....mi sfugge qualcosa o ho preso male l'appunto :(

**Comment by aborruso** [comment]
Manca l'ultima guida da scrivere. Un po' di pazienza.

Mi incolli anche qui l'URL del foglio di partenza, e mi dai i permessi in
scrittura?

Il giorno dom 20 dic 2015 14:54 giuragu84 notifications@github.com ha
scritto:

**Comment by giuragu** [comment]
@aborruso subito....https://docs.google.com/spreadsheets/d/1_nroXRYhkKpw0bAcvoYjFHwdQ5eL85ITucR7FRrRFLE/edit?usp=sharing

**Comment by aborruso** [comment]
Ho creato all'interno un nuovo foglio chiamato output, per generare una versione pulita e ordinata dei dati raccolti.

E' necessario che esista, le righe e le celle vuote sono un disturbo. Per ora senza spiegazioni.

![image](https://cloud.githubusercontent.com/assets/30607/11918771/6ae1d696-a73f-11e5-8211-9af256858612.png)

**Comment by giuragu** [comment]
Ricevuto :) @aborruso

**Comment by aborruso** [comment]
Ecco la guida importante che mancava: [Gdrive: pubblicare uno sheet come HTML e predisporlo allo scraping con Kimono](https://github.com/aborruso/albo-pop/wiki/Gdrive:-pubblicare-uno-sheet-come-HTML-e-predisporlo-allo-scraping-con-Kimono)
