### ISSUE TITLE
AlboPop Verbania

### ISSUE THREAD

**Issue by pietrondo** [aborruso/albo-pop#221]
Ciao volevamo segnalare l'albo Pop del comune di  Verbania (Piemonte) con relativo canale telegram

Rss: http://feeds.feedburner.com/google/CKbM
Canale telegram: https://telegram.me/AlboPopVB

**Comment by aborruso** [comment]
Ciao @pietrondo grazie per avere contribuito e complimenti.

Ho messo te come autore: [http://albopop.it/comune/verbania/](http://albopop.it/comune/verbania/)

Fammi sapere se devo cambiare qualcosa

**Comment by pietrondo** [comment]
Ciao c'è un errore nella pagina hai scritto: La pagina dell’albo pretorio
del comune di

_Barcellona Pozzo di Gotto .._
_grazie_

Pietro Capriata

http://www.pietrocapriata.me

CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by aborruso** [comment]
fatto!
