### ISSUE TITLE
Creare Albopop Manerbio (BS)

### ISSUE THREAD

**Issue by ebergam** [aborruso/albo-pop#226]
Un assessore comunale di Manerbio, che è un giovanotto amico mio (e tra l'altro cura un bel [blog](http://www.fabriziobosio.it/)), mi ha chiesto di fare albopop di Manerbio. L'albo è questo [qua](http://asp.urbi.it/urbi/progs/urp/ur1ME001.sto) :)

**Comment by aborruso** [comment]
Caro @ebergam il sito in oggetto è uno di quelli che non ha un vero URL che ti porta alla pagina con la lista degli atti pubblicati. Se apri una sessione anonima e usi il tuo URL, ottieni 

![image](https://cloud.githubusercontent.com/assets/30607/21080750/0c4f11b6-bfb7-11e6-9e64-fab998a7bc4e.png)

C'è da fare infatti un invio dati via Post.

Allora ho creato un clone sul server onData, che si aggiorna ogni 20 minuti [http://dev.ondata.it/projs/albopop/manerbio/](http://dev.ondata.it/projs/albopop/manerbio/)

Si potrebbe allora semplicemente faro lo scrape su questo.

L'URL della richiesta alla pagina di dettaglio è 

    http://asp.urbi.it/urbi/progs/urp/ur1ME001.sto?StwEvent=102&DB_NAME=n1200776&IdMePubblica=1865&Archivio=

Ciò che è variabile è l'ID. Sopra è [1865](http://asp.urbi.it/urbi/progs/urp/ur1ME001.sto?StwEvent=102&DB_NAME=n1200776&IdMePubblica=1865&Archivio=), e questo è ad esempio [1867](http://asp.urbi.it/urbi/progs/urp/ur1ME001.sto?StwEvent=102&DB_NAME=n1200776&IdMePubblica=1867&Archivio=).

**Comment by ebergam** [comment]
Grazie mille @aborruso ! Non riesco a vedere il clone però, mi si apre ma è una pagina vuota

**Comment by aborruso** [comment]
@ebergam usa questo per ora [http://blog.spaziogis.it/static/projs/albopop/manerbio/](http://blog.spaziogis.it/static/projs/albopop/manerbio/)

**Comment by ebergam** [comment]
Grazie mille Andy :)

**Comment by aborruso** [comment]
@ebergam appena puoi per favore imposta nuovamente come source questo [http://dev.ondata.it/projs/albopop/manerbio/](http://dev.ondata.it/projs/albopop/manerbio/)

Ho sistemato tutto

**Comment by ebergam** [comment]
Fatto, grazie  :)

2016-12-11 20:11 GMT+01:00 Andrea Borruso <notifications@github.com>:
