### ISSUE TITLE
AlboPop Bitonto: come caricare le pagine successive alla prima ?

### ISSUE THREAD

**Issue by sputnik63** [aborruso/albo-pop#227]
Ho creato gli albi di Terlizzi e Bitonto entrambi prov BA ma l'albo di Bitonto (e forse anche altri albi) soffre di un problema.
Il link è questo:
http://bitonto.trasparenza-valutazione-merito.it/web/trasparenza/albo-pretorio
e a causa della sua struttura non è possibile richiamare con i fogli google le pagine successive alla prima.
Ho notato che l'impiegato zelante del comune lo scorso lunedì ha postato ben 104 nuovi documenti e così il canale telegram si è perso tutti gli 84 documenti successivi ai primi 20.
E' ricapitato ieri quando ne sono stati pubblicati 24.
Non so come risolvere il problema. Credo che per come è implementato il sito non sia possibile ma potrei sbagliarmi.
Ci sono altri albi che hanno questo problema ?

**Comment by aborruso** [comment]
ciao @sputnik63 sugli albi Jcitygov ha lavorato @mfortini e credo abbia risolto il problema di cui parli puntando direttamente al CSV. Quello di Bitonto è [questo](http://bitonto.trasparenza-valutazione-merito.it/web/trasparenza/albo-pretorio?p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=exportList&p_p_cacheability=cacheLevelPage&p_p_col_id=column-1&p_p_col_count=1&_jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet_format=csv).

Nello spreadsheet, per i CSV, puoi usare la funzione IMPORTDATA e poi tramite la funzione QUERY rimontarti le varie colonne. In casi come questi alle volte l'ostacolo è la lentezza di download del CSV e di solito prima di passarlo a gdrive faccio un download su un server "mio". Se serve posso crearti uno script che ogni 24 ore lo aggiorna e poi carica qui sul repo di albopop il CSV aggiornato.

Il codice che ha costruito @mfortini è questo https://github.com/aborruso/albo-pop/tree/master/code/jCityGov

Facci sapere

**Comment by sputnik63** [comment]
Ok. Vorrei provare. Contattami in privato per darmi indicazioni su come usare lo script

**Comment by cristianolongo** [comment]
prova 

http://bitonto.trasparenza-valutazione-merito.it/web/trasparenza/albo-pretorio;jsessionid=67943DFF9785B95D809506D1B758CFA8?p_auth=P6lyGejW&p_p_id=jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_jcitygovalbopubblicazioni_WAR_jcitygovalbiportlet_action=eseguiPaginazione&hidden_page_size=200

Il parametro hidden_page_size è il numero di entries per pagina, normalmente questi albi non arrivano a 170.

**Comment by sputnik63** [comment]
Causa un piccolo remake delle pagine di questo Albo sono tornato sul problema e la soluzione di @cristianolongo è ok. Grazie
