### ISSUE TITLE
Canale Telegram di AlboPopBari non trovato

### ISSUE THREAD

**Issue by sputnik63** [aborruso/albo-pop#229]
Il canale telegram menzionato nel file bari.md non esiste.
Il feed riporta il titolo errato (Surbo) e non riporta tutti i documenti in albo ma solo una parte

**Comment by aborruso** [comment]
Lancio un ping a @piersoft

**Comment by piersoft** [comment]
ho corretto il titolo e mi sembra che il feed funzioni. Non ho creato bari.md perchè c'è solo il feed. @aborruso creo lo stesso?

**Comment by aborruso** [comment]
@piersoft lo stiamo facendo sempre, anche con solo feed RSS, che in fondo è la cosa che conta.

Ci penti tu?

Grazie

**Comment by piersoft** [comment]
fatto.

2016-12-08 17:50 GMT+01:00 Andrea Borruso <notifications@github.com>:

**Comment by piersoft** [comment]
si ci ho "pentito" io :)

Piersoft
Inviato da iPhone

**Comment by aborruso** [comment]
grazie @piersoft
