### ISSUE TITLE
Encoding dell'URL di Marineo

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#23]
Il feed RSS del Comune di Marineo espone gli URL in questo modo:

"http://www.albipretori.it/Public/Pubblicazioni.aspx?Codice=86&amp;IdPubblicazione=3431"

Pubblicato su un canale Telegram viene troncato in "http://www.albipretori.it/Public/Pubblicazioni.aspx?Codice=86" e quindi non punta correttamente al singolo item.

**Comment by aborruso** [comment]
Basta sostituire `&amp;IdPubblicazione=` con `%26IdPubblicazione%3D`

Con sed ad esempio: 

```
sed -e "s/&amp;IdPubblicazione=/%26IdPubblicazione%3D/g" input.xml > output.xml
```

**Comment by cirospat** [comment]
grazie Andrea

Il giorno 21 dicembre 2015 13:36, Andrea Borruso notifications@github.com
ha scritto:
