### ISSUE TITLE
Richiesta di Donazioni nelle pagine condivise degli albi gestiti da opendatahacklab

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#231]
Vorremmo aggiungere un link per fare una donazione ad Hackspace Catania nelle pagine di avvisi che condividiamo su facebook.  Vorrei sapere se qualcuno ha qualcosa in contrario

**Comment by nelsonmau** [comment]
non ho ben capito

**Comment by cristianolongo** [comment]
I nostri albi non puntano direttamente alla pagina web dell'avviso sul sito della PA, ma una pagina di passaggio che usiamo per veicolare dei messaggi e iniziative. Queste pagine hanno anche un pulsante di condivisione su facebook. Un esempio è questo:

http://dev.opendatasicilia.it/albopop/unict/sharer.php?number=1025

Vorremmo inserire in altro un messaggio del dipo "Sostieni questo Albo POP con una donazione"
e il link alla ppagina di donazioni per Hackspace Catania.

**Comment by riccardomariagrosso** [comment]
Pienamente in accordo
Il 09/nov/2016 11:05 "Cristiano Longo" notifications@github.com ha
scritto:

**Comment by nelsonmau** [comment]
ok @cristianolongo quindi tu dici: nella pagina come questa http://dev.opendatasicilia.it/albopop/unict/sharer.php?number=1025 mettere un annuncio in cui dici "Sostieni opendatahacklab"

per me non problem :)

l'unico dubbio lo avrei se l'annuncio apparisse su albopop.it, o un'altra pagina su questo dominio, ma mi pare non sia questo il caso. Se vuoi ti spiego anche il perché del dubbio, è una cosa un po' lunga

**Comment by cristianolongo** [comment]
Deve essere chiaro che la donazione non va a tutta la comunità di albo pop ma solo a chi gestisce lo specifico dubbio. Quando hai tempo ti ascolto.

**Comment by nelsonmau** [comment]
@cristianolongo ok capito :)

dunque: mentre i feed rimangono ovviamente indipendenti, il sito albopop.it ha bisogno di un server perché il motore di ricerca (cerca.albopop.it) è basato su elastichsearch, ha sotto un db, e ha dei sistemi che archiviano/indicizzano.

Il server di albopop non può essere il server di dataninja, ma ne occorre un altro. Siccome l'associazione Ondata non aveva un server, abbiamo deciso di acquistarlo e far convergere lì tutte le cose di ondata, come albopop, confiscatibene, etc. 

quindi albopop.it (che ovviamente, manco a dirlo, rimane aperto) va sotto server ondata e ondata che autofinanzia la cosa potrebbe un domani dire: "sostienici per tenere acceso il sito". Non abbiamo ancora avuto tempo di parlarne, quindi è una mia idea, ma la proporrei più avanti.
Non possiamo però duplicare le cose, ecco perché avrei dubbio di un doppio messaggio di sostegno. Per cui quello che vedo io è:
- gli albipop catanesi o altri intesi come feed vengono fatti da gruppi di lavoro che dicono "sostienici se vuoi che continuiamo e tenere vivi i feed"
- il _sito_ albopop.it e cerca.albopop.it possono invece stare sul server di ondata che dice "sostienici se vuoi che il sito resti acceso".

non so se l'ho spiegata bene, dimmi tu, e anzi dimmi la tua opinione pls :)

**Comment by cristianolongo** [comment]
On 09/11/2016 11:43, Andrea Nelson Mauro wrote:

> @cristianolongo https://github.com/cristianolongo ok capito :)
> 
> Il server di albopop non può essere il server di dataninja, ma ne 
> occorre un altro. Siccome l'associazione Ondata non aveva un server, 
> abbiamo deciso di acquistarlo e far convergere lì tutte le cose di 
> ondata, come albopop, confiscatibene, etc. 
> Eh ma di ste cose parliamone prima, albo pop ad esempio potrebbe andare 
> sul server di opendatasicilia.

CL

**Comment by nelsonmau** [comment]
@cristianolongo opendatasicilia non è un soggetto giuridico, non può avere un server a nome proprio

**Comment by nelsonmau** [comment]
@cristianolongo scusami, giornataccia, oggi sono intermittente. 
Dunque dicevo: ODS non è un soggetto giuridico e non può avere un server. Il server che c'è adesso per opendatasicilia è offerto gratuitamente da alcuni soggetti, come fatto da dataninja fin qui. 
Che senso avrebbe cambiare?

La proposta di cambiamento che ho fatto a Ondata è di sostenere Albopop, ospitandolo su un server dedicato insieme ad elastichsearch. Banalmente essendo @aborruso presidente di ondata, ho fatto presto a proporglielo :)

Ospitando sul proprio server Albopop.it, ondata ne garantisce il funzionamento, come anche il funzionamento del motore di ricerca (che è quello a cui poi serve realmente il server). È un modo per garantire che tutto funzioni e stia in piedi, specie visto che l'associazione si è data questo obiettivo: sostenere cose, progetti e comunità alle quali serve aiuto 

Inoltre dataninja ha donato il codice di cerca.albopop.it al progetto e a ondata. Quindi non vedo in effetti lacune nel processo decisionale o di condivisione, ma anzi vedo il fatto che stiamo cercando di garantire lunga vita al progetto, ben sapendo che lo facciamo come "tempo libero" e mettendo risorse nostre

Non credi sia così? Mi sto perdendo qualche passaggio?
grassie!

**Comment by cristianolongo** [comment]
Ne parliamo in privato.
