### ISSUE TITLE
Albo Pop Manduria

### ISSUE THREAD

**Issue by Gabrieleiurlaro** [aborruso/albo-pop#234]
@aborruso ,Buonasera! Vorrei avviare il progetto Albo Pop a Manduria, a cui tengo particolarmente anche se non sono residente lì. Ti lascio il link dell'Albo pretorio, puoi vedere se si può fare qualcosa?

http://www.comune.manduria.ta.it/albo-pretorio

@piersoft si può fare qualcosa per un canale telegram?

**Comment by Gabrieleiurlaro** [comment]
Mi scuso se la mia richiesta vi ha dato fastidio, posso capire che vi siate rifiutati, ma almeno una risposta, in 17 giorni la potevate dare(anche se negativa). Un'ultima cosa, è un sassolino che mi voglio levare dalla scarpa, vi professate fautori della riforma open in italia, ma senza soldi, o per altri interessi, non fate niente. Grazie comunque, eviterò di farvi perdere altro tempo.

**Comment by piersoft** [comment]
http://feeds.feedburner.com/Newspopmanduria riesci a metterlo tu nell'elenco dei comuni qui su albo pop e poi crei il canale telegram o hai bisogno di una mano?

**Comment by Gabrieleiurlaro** [comment]
Una mano è molto gradita, grazie

**Comment by Gabrieleiurlaro** [comment]
Ho aggiunto il comune nella cartella _comune, come devo procedere per il canale telegram? Uso IFTTT?

**Comment by simoneversienti** [comment]
@piersoft Do una mano io per il canale Telegram.

**Comment by piersoft** [comment]
nel wiki c'è scritto come integrare ifttt. se vuoi c'è anche un post su piersoft.it come collegare un automa che legga i feeds verso telegram. da ieri nella nuova app telegram, c'è anche @ifttt integrato per fare tutto da dentro lo smartphone

Piersoft
Inviato da iPhone

**Comment by Gabrieleiurlaro** [comment]
Garzie mille, ho già creato il canale!

**Comment by piersoft** [comment]
mi contatti su telegram @piersoft cosi ti guido passo passo

Piersoft
Inviato da iPhone

**Comment by Gabrieleiurlaro** [comment]
@piersoft, ho già creato il canale, l'ho anche automatizzato con IFTTT. Lascio qui il link: https://telegram.me/albopopmanduria

Ho già controllato e funziona.

**Comment by piersoft** [comment]
ok sei capace a creare manduria.md nell'elenco delle città? 

Piersoft
Inviato da iPhone

**Comment by aborruso** [comment]
@Gabrieleiurlaro grazie per quello che hai stimolato e fatto! E grazie @piersoft 

Ho aggiunto la pagina [http://albopop.it/comune/manduria/](http://albopop.it/comune/manduria/)

Se devo modificare qualcosa, fate un fischio
