### ISSUE TITLE
Albo POP Grottaglie (TA)

### ISSUE THREAD

**Issue by simoneversienti** [aborruso/albo-pop#239]
Salve a tutti.
Prima di spiegare il problema faccio una premessa: l'albo di Grottaglie è organizzato in tre sezioni distinte. 
[http://195.120.113.106/webfolder01/openweb/internet/web//portal/index.php](url)
Un po' di tempo fa ho provato a creare un feed RSS partendo dalle delibere di consiglio [http://195.120.113.106/webfolder01/openweb/internet/web//pratiche/registri.php?codEstr=DELB](url) arrivando a questo: [https://script.google.com/macros/s/AKfycbzmGTCzyO5BMN4d9aSyVXJTCIVMcMmKVXCFLCiUMBvYnKBQwtFR/exec](url)
Come vedrete, però, la data è sbagliata (01/01/70).
In più io vorrei creare tre feed RSS, uno per ogni sezione o, ancor meglio, uno che racchiuda le inserzioni di tutte e tre le sezioni.
Confido in un vostro aiuto...spirito di @piersoft , io ti invoco 😛

**Comment by aborruso** [comment]
Ciao @simoneversienti parto da un consiglio di base: è meglio impostare il foglio elettronico con una localizzazione UK (o USA). Questo perché lo standard delle date per gli RSS poi si deve esprimere in "inglese". Avrai `Thu, 27 Oct 2016 00:00:00 +0200` e non `Gio, 27 Ott 2016 00:00:00 +0200`.

Per farlo apri le proprietà del foglio creato e fai come sotto:

![image](https://cloud.githubusercontent.com/assets/30607/21079932/a4cca5c2-bfa1-11e6-8a61-a20b6b9f7dfb.png)

Poi, potrai pure convertire la data in formato RSS sempre dentro il foglio, usando la funzione `TEXT` di [gdrive](https://support.google.com/docs/answer/3094139?visit_id=1-636170544148125181-3843213008&hl=en-GB&rd=1).

[Qui](https://docs.google.com/spreadsheets/d/1llGlLdKPseNJDz6RgNSS-D1XRTZsk173rwyDEj2LPbA/edit#gid=0) un esempio di foglio in cui importo la data e la converto in formato corretto.

Se vuoi, condividi qui il tuo foglio che produce date "sbagliate".

**Comment by simoneversienti** [comment]
Ecco @aborruso 
[https://docs.google.com/spreadsheets/d/1TMvFCy78bWNSo82sFNe5aPMK3uSGfer6BUTfZ3c9jmg](url)

**Comment by aborruso** [comment]
@simoneversienti l'ho aperto, ma qui non c'è nessuna data. Hai 1/1/70 perché è tutto vuoto.

Ok, quindi è proprio tutto da costruire.  Ho capito bene?

**Comment by simoneversienti** [comment]
@aborruso appena posso setto la data seguendo le tue indicazioni...vi aggiorno

**Comment by simoneversienti** [comment]
@aborruso niente da fare, è tutto da costruire.

**Comment by simoneversienti** [comment]
@aborruso @piersoft 
Questo è il foglio: [https://docs.google.com/spreadsheets/d/1KauFFOINrUgCZoZTrJ03CMY2FMjajh5SnulwmvumblQ/edit?usp=sharing](url)
e questo è l'RSS che ottengo [https://script.google.com/macros/s/AKfycbzviupo0UxU628VuosOJXPAhlgXJmr4IUFqFifn5X2Wjvc5pSg/exec](url)
Come data sempre 01/01/70

**Comment by simoneversienti** [comment]
@piersoft Mi ha dato una grossa mano, tutto ok ora, chiudo.
