### ISSUE TITLE
Articolo sul wiki riportato da un altro blog

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#247]
Ciao ho scritto sul mio blog della vita fuori da facebook un articolo che racconta le attività che svolgo con albo pop.

https://cristianolongo.wordpress.com/2017/02/10/la-giornata-tipica-dellattivista-albo-pop/

mi chiedo se è il caso di riportarlo anche sul wiki di del sito albopop.it

**Comment by aborruso** [comment]
@cristianolongo perché non lo pubblichi anche come post [qui](https://github.com/aborruso/albo-pop/tree/gh-pages/_posts), mettendo in testa l'URL alla fonte originaria?

**Comment by cristianolongo** [comment]
ho l'impressione che non venga pubblicato

**Comment by aborruso** [comment]
È online http://albopop.it/La-giornata-tipica-dellattivista-Albo-POP/
