### ISSUE TITLE
Tracciamento avvisi sull'albo di Catania 

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#259]
Salvare su un log ogni giorno gli avvisi che compaiono nell'albo (solo il numero) . Serve a verificare il corretto funzionamento dell'albo.

**Comment by sputnik63** [comment]
in quelli da me monitorati tramite gsheet se trovo un campo nullo mi genero l'invio di una email. Ha funzionato già una volta. Potrebbe essere una alternativa (o affiancamento) al log

**Comment by cristianolongo** [comment]
@sputnik63 se non ho capito male quello che hai tu serve a capire se l'albo è offline.

**Comment by sputnik63** [comment]
Non proprio. Tramite IMPORTXML recupera l'ultimo dei campi "Titolo" e, se lo trova nullo, manda una email tramite gscript. Lo ho messo su anche per farmi notificare (in modo grossolano) una eventuale improvvisa diversa paginazione del sito
