### ISSUE TITLE
AlboPOP di Manerbio si è impallato

### ISSUE THREAD

**Issue by ebergam** [aborruso/albo-pop#269]
@aborruso quando hai 5 minuti dai un occhio sul server di ondata che secondo me il primo pezzo che avevi fatto tu gira lì :)

**Comment by aborruso** [comment]
sul server è stato disinstallato un componente.

Per ora ho migrato tutto. Inserisci come fonte per favore questo URL http://blog.spaziogis.it/static/projs/albopop/manerbio/

Grazie

**Comment by ebergam** [comment]
Grazie mile Andy! Cambiato negli sheets, aspetto che riparta tutto e chiudo l'issue
