### ISSUE TITLE
Call per merge-it

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#279]
Ciao Amici, quest'anno per la prima volta le comunità dell'openness si riuniscono in un evento unificato chiamato merge-it (24 Marzo a Torino)

https://merge-it.net/

Ho sempre pensato ad albo pop come uno strumento a forte vocazione locale (think global, act local!). I Linux User Group sono una rete capillare di esperti diffusa nei territori e con vocazione "Libera". Come tali a mio avviso sarebbero il canale ideale per diffondere ed aiutare le persone ad usare albo pop e più in generale gli albi in RSS. 

Perchè i LUG potrebbero essere interessati?

Perchè Albo POP usa un protocollo aperto, RSS (Aaron R.I.P.). Esistono svariati strumenti aperti per la fruizione dei feed RSS, io consiglio sempre thunderbird. In pratica potrebbe essere per loro l'occasione di promuovere un software libero come thunderbird. NB: fuck capitalism e tutti i suoi figliastri da whatsup a telegram a facebook!

Quindi in pratica ci sarebbe da fare un talk nel pomeriggio del 24 marzo. Qualcuno vuol dare una mano?

Un bacio,
CL

**Comment by aborruso** [comment]
@cristianolongo facciamo una call in settimana? La settimana prossima? Proponi tu le modalità.

Grazie

**Comment by cristianolongo** [comment]
scusa me lo ero perso, ci penso un attimo. Intanto ho elaborato un testo

Titolo: Albi Pretori ed RSS - Verso un Hacking della Pubblica Amministrazione

Testo: Tutte le pubbliche amministrazioni Italiane sono obbligate a pubblicare in un apposito spazio del proprio sito web tutti gli atti e le notizie di interesse pubbliche che la riguardano. Osservando gli avvisi che compaiono in albo è possibile comprendere il funzionamento di una Pubblica Amministrazione ed utilizzare appieno ed in maniera "adeguata" i servizi che offre o dovrebbe offire.

La consultazione della pagina web però non può essere una modalità effettiva per il monitoraggio di una PA. Per questo motivo la comunità di Albo POP studia nuove modalità di analisi, trattamento e disseminazione degli avvisi presenti negli albi pretori. Il principale di questi strumenti sono i feed RSS, implementati tramite un protocollo aperto (appunto RSS) e fruibile attraverso molteplici software proprietari o liberi.

Lo scopo di questa sessione è di mostrare l'esperienza di Albo POP, le difficoltà riscontrate e discutere insieme del suo futuro e di possibili evoluzioni.

**Comment by aborruso** [comment]
@cristianolongo mi pare lineare e mi piace. Grazie

**Comment by cristianolongo** [comment]
appena ricordo come si chiama lo strumento per decidere gli appuntamenti metto un elenco di date proposte per la call. Facciamo su IRC così i nostri rumori non inquineranno il pensiero.

**Comment by bertalan** [comment]
doodle

2018-02-08 23:20 GMT+01:00 Cristiano Longo <notifications@github.com>:
