### ISSUE TITLE
Nuovo albo-pop

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#280]
Buongiorno a tutti,
dopo tanto tempo mi sono deciso - grazie allo stimolo e alla collaborazione di molti -  di dare nuova linfa, struttura e vita a questo progetto. 
Ha vissuto fino ad ora quasi di vita di propria, con stimoli e contributi da varie fonti, ma per dargli ancora spazio e tempo ha bisogno di crescere.

Con la mia associazione (onData), abbiamo in corso due progetti dove l'uso dell'albo alla "albo-pop" è un prerequisito. Sono due progetti in cui abbiamo investito e abbiamo delle risorse da dedicare.
Una delle prime cose che farò presto, è spostare questo repo da un mio account personale (non ha più senso) all'account di ondata come organizzazione.

Non cambierà né lo spirito, né la licenza, né le specifiche sullo schema di un albo. Dettaglierò di più in un nuovo messaggio. Per ora mi limito a un sentito grazie, a tutti quelli che hanno contribuito al progetto e che potranno ovviamente continuarlo a fare.

Buona giornata

**Comment by aborruso** [comment]
Ho terminato il passaggio sull'organizzazione onData

**Comment by piersoft** [comment]
grazie Andrea.
Speriamo che il progetto prenda nuova linfa come dici (magari si estende ad ArpaPop) e con lo stesso spirito.
