### ISSUE TITLE
Integrare "gare" ad AlboPOP Campobello di Licata

### ISSUE THREAD

**Issue by matteoscire** [aborruso/albo-pop#30]
Il sindaco del Comune di Campobello di Licata mi ha chiesto di integrare nell'AlboPOP anche le gare. Queste, infatti, non vengono pubblicate sull'Albo online ma in un link omonimo del sito.
Questo è l'rss: https://www.kimonolabs.com/api/rss/461acvi8?&apikey=utlI5xKmMbisI2JUNPIBuikcBOLU5I76&kimmodify=1

**Comment by aborruso** [comment]
@matteoscire ti direi di stoppare la ricetta in IFTTT, per questo feed, perché vedo elementi senza titolo.

Ci lavoro e ti faccio sapere

![2016-01-04_12h54_10](https://cloud.githubusercontent.com/assets/30607/12089177/47655a4a-b2e2-11e5-84c4-6fa508115a4f.png)

**Comment by aborruso** [comment]
@matteoscire adesso dovrebbe andare. Non appena hai riscontri, please chiudi la issue
