### ISSUE TITLE
commentare codice kimono nel wiki

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#31]
Commentare [questa parte](https://github.com/aborruso/albo-pop/wiki/Kimonolabs#modificare-loutput-di-kimono-in-modo-che-title-e-link-del-feed-rss-siano-correttamente-mappati) del wiki, altrimenti non è comprensibile ad alcuno.

**Comment by ebergam** [comment]
Fatta una parte

**Comment by aborruso** [comment]
Grazie mille @ebergam
