### ISSUE TITLE
esercitazione albo isola

### ISSUE THREAD

**Issue by grimaldi1972** [aborruso/albo-pop#36]
Gdrive su albo caso molto interessante uso didattico xpath
vedi file:
https://docs.google.com/spreadsheets/d/1P-1Ke1yX32vvMNZzDvGGmg5Zq48KxlaMArqAeshu0PU/edit#gid=0

Per il titolo ad esempio: `//tr[td[4] > 0]/td[5]`
Che vuol dire:
- a partire da tutte le righe di  una tabella `//tr`
- estrai soltanto quelle righe in cui la 4 colonna ha valori maggiori di 0 `//tr[td[4] > 0]`, così ti eviti le righe di intestazione e le righe in fondo con avanti;
- e poi tira fuori quanto trovi nella colonna 5 `//tr[td[4] > 0]/td[5]`

x info naturalmente @aborruso

**Comment by aborruso** [comment]
@grimaldi1972 ti sei arreso? :)

**Comment by grimaldi1972** [comment]
No, scoraggiato si. Soprattutto quando vedi le competenze degli altri che si presentano con albopop belli e fatti e io che mi perdo nei buchi neri di ogni singolo nuovo strumento.
L'albo di Isola delle Femmine ha il difetto che non il link diretto ad ogni singolo documento viene bloccato dal sito:
http://alboisoladellefemmine2.intradata.it:8080/ttcom/servlet/readfile?8Mn342hD43008saddsfsaffa44twg5sfsfsfasLsd8fdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfasf3k3=92975&yyygdsgasdgsadgasgsdgadgadgy=pdf&PERCORSO=2016&NOME=92975

Avere la notifica della pubblicazione all'albo potrebbe essere già un info:
il docs funziona correttamente, mentre Rss generato non si aggiorna:
https://www.kimonolabs.com/api/rss/4fbn2gsq?apikey=j1EDoR5py5DQK6R76jt85wU1zCMzTrdS

Come mi hai suggerito ho creato canale telegram e twitter .. ed ho iniziato a piangere, "mancu un bip"
I miei dati:
https://twitter.com/albopopisola
@albopopisola

rss kimonolabs
grimaldi1972@libero.it
Utente01
https://www.kimonolabs.com/api/rss/4fbn2gsq?&apikey=j1EDoR5py5DQK6R76jt85wU1zCMzTrdS&kimmodify=1

IFTTT
mariogrimaldi743isola
Utente01

Recipe ID 32220155

Telegram

canale
https://telegram.me/alboisoladellefemmine

@Grimaldi_bot
141096370:AAEuPGfKgDjOXhBH579JX2lrSMmBzSZphGQ

https://api.telegram.org/bot141096370:AAEuPGfKgDjOXhBH579JX2lrSMmBzSZphGQ/sendMessage

chat_id=@alboisoladellefemmine&text= {{EntryTitle}} {{EntryUrl}}

Forse ho scelto un albo poco indicato come principiante.
Grazie.

**Comment by joska1978** [comment]
ciao mario! 
ho parlato l'altro ieri con la dipendente del comune di isola delle femmine che si occupa della gestione dell'albo pretorio on line (cinzia cardinale). 
si è dimostrata disponibile in caso a verificare le problematiche inerenti l'albo per vedere come si deve agire e quali criticità sono presenti e come superarle. per quanto riguarda l'amministrazione comunale di isola (a livello assessori della giunta) le condizioni poi per discutere con calma dell'implementazione dell'albo pop si possono creare, una volta risolte queste problematiche tecniche.

i rapporti di questi tempi sono costanti e positivi per poter creare le condizioni.

se vuoi organizziamo l'incontro con cinzia cardinale e vediamo insieme il da farsi.

che dici?

**Comment by joska1978** [comment]
se sei d'accordo potremmo contemporaneamente provare anche con quello del comune di CAPACI che si presta meglio all'implementazione dei canali e ti permette di lavorarci meglio.

**Comment by joska1978** [comment]
ho già avviato dei contatti con alcuni assessori e consiglieri comunali di capaci a cui ho strappato almeno un interessamento e un incontro da organizzare a febbraio per discutere e far conoscere l'albo pop.

stessa cosa e anzi un pò più avanzata anche l'avvicinamento alla discussione in seno alla giunta e alcuni consiglieri comunali anche per il comune di CARINI.

SU TRE COMUNI..almeno se ne realizziamo uno/due direi che è un buon risultato in merito.

**Comment by grimaldi1972** [comment]
E' rimasta aperta
https://github.com/aborruso/albo-pop/issues/2

**Comment by grimaldi1972** [comment]
Certamente, con albopop di isola delle femmine mi sono arenato, non semplice da gestire, magari a prodotto finito possiamo fissare un incontro.
Albo capaci, provo a fare qualcosa e non appena abbiamo qualcosa in mano, ci facciamo sentire.
Grazie @joska1978

**Comment by grimaldi1972** [comment]
Albo Isola delle Femmine: @joska1978 sembrerebbe funzionare.
•account Twitter https://twitter.com/albopopisola
•canale Telegram https://telegram.me/alboisoladellefemmine
•feed RSS http://feeds.feedburner.com/AlboPretorioIsolaDelleFemmine
