### ISSUE TITLE
Aggiungere Bondeno

### ISSUE THREAD

**Issue by ebergam** [aborruso/albo-pop#37]
Bondeno (Emilia-Romagna)
La pagina dell'albo pretorio del Comune di Bondeno è questa: http://sac2.halleysac.it/c038003/mc/mc_p_ricerca.php?

Adesso puoi seguire le nuove pubblicazioni in albo in quattro modi dedicati:

su un account Twitter https://twitter.com/AlboPOPBondeno;
su un canale Telegram https://telegram.me/albopretorioBondenoFe;
su una pagina Facebook https://www.facebook.com/Albo-Pretorio-POP-Bondeno-FE-1535959506725000/a?fref=ts
iscrivendoti a un feed RSS: http://feeds.feedburner.com/AlbopopbondenoFE

**Comment by ebergam** [comment]
aggiunto

**Comment by aborruso** [comment]
Piango dalla gioia :)

Certo una pagina sul wiki che abbozza come si fa a pubblicare un nuovo comune ...
