### ISSUE TITLE
Pagina Facebook albo POP unict

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#38]
Creare una pagina facebook apposita e una ricetta IFTTT che mandi i post su quella pagina.

**Comment by ebergam** [comment]
Non so se ti serva ma ti allego la ricetta fatta per l'albopop di bondeno. L'unico limite su cui bisogna ragionare è che ifttt ti dà la possibilità di connettere solo una pagina su cui mandare roba, e se voglio amministrarne un'altra con ifttt devo usare un qualche workaround.

![iftttpop](https://cloud.githubusercontent.com/assets/13796570/12121110/ec009f14-b3d3-11e5-8782-42bf3de6186c.png)

**Comment by cristianolongo** [comment]
Grazie mille!
