### ISSUE TITLE
Albi Pretori J-City Gov di Maggioli

### ISSUE THREAD

**Issue by mfortini** [aborruso/albo-pop#45]
Alcuni Comuni hanno acquistato per l'Albo Pretorio i servizi di Maggioli http://www.maggioli.it/informatica/servizi-egovernment/

Esempio:
- Cento http://servizi.comune.cento.fe.it/web/trasparenza/albo-pretorio
- Pisa http://albopretorio.comune.pisa.it/web/trasparenza/albo-pretorio
- Collegno http://atti.comune.collegno.gov.it/web/trasparenza/albo-pretorio
- Monteriggioni http://monteriggioni.trasparenza-valutazione-merito.it/web/trasparenza/albo-pretorio
- Alghero http://94.95.21.38/web/trasparenza/albo-pretorio
- Rivarolo (MN) http://trasparenza.comune.rivarolo.mn.it/albo-pretorio
- Latina http://trasparenza.comune.latina.it/web/trasparenza/albo-pretorio

Tutti questi "portali" hanno un link in basso a sinistra che permette di ricavare il CSV con i dati attuali. Sarebbe sufficiente monitorarli e convertirli in RSS per poi darli in pasto a IFTTT o Zapier e lanciarli su Twitter/Telegram etc

**Comment by mfortini** [comment]
Ho usato =IMPORTDATA() per importarli in Google Spreadsheet, ma pare che la nuova versione di Spreadsheet non permetta più di esportare i dati come RSS
https://productforums.google.com/forum/#!topic/docs/nPmu4qMIHTo;context-place=topicsearchin/docs/publish$20spreadsheet$20rss

**Comment by aborruso** [comment]
@mfortini  finché non abbiamo un server (e fra poco penso che l'avremo) potresti esporre il foglio elettronico in cui hai fatto `IMPORTDATA()` come pagina HTML, su questa fare lo scraping con kimono e il contestuale export in RSS.

Molti albi POP attualmente funzionano quasi così (fanno in realtà l'import tramite query XPATH sempre su un foglio).

**Comment by aborruso** [comment]
@mfortini a proposito dell'output in RSS da gdrive è vero.

Però c'è una strada che secondo me varrebbe la pena di esplorare e mettere in piedi. Io non mi ci posso dedicare adesso. La lancio qui :)

Questo foglio l'ho reso visibile a tutti:
https://docs.google.com/spreadsheets/d/1Tc_eoyQTtRmnncdPw934roxmyuLIOH3FJBNi0mMmJus/edit?usp=sharing

L'output in JSON:
https://spreadsheets.google.com/feeds/list/1Tc_eoyQTtRmnncdPw934roxmyuLIOH3FJBNi0mMmJus/od6/public/basic?alt=json

L'output in XML:
https://spreadsheets.google.com/feeds/list/1Tc_eoyQTtRmnncdPw934roxmyuLIOH3FJBNi0mMmJus/od6/public/values

Si potrebbe creare uno google app script che accede a una di queste due source, ne estrae i valori e li ributta fuori secondo uno schema RSS utile.

Quello di sotto è uno script ciao mondo che ho trovato [qui](https://developers.google.com/apps-script/guides/content), che ho testato, deployato come web app, e che restituisce a runtime [questo](https://script.googleusercontent.com/macros/echo?user_content_key=XMoA0WbzsoP980bQhaGurMIZdzyPnhpe_xTNr6PBkhDR4ukb219fmt0kO3r74KKUlLFHOBNXku-bouDfOQ7Z70dJOvohIP5Sm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnMyilKFolBFbplSfHXv07uNDwH24-glPA-Yr4HOvvFGSdBX-725CtNh31pdTjCpudxdIug5zkO6q&lib=M-TJRnvz18aaHklUgnT5wcTcqYDhQuE81) feed RSS.

E' chiaro, nello script da creare c'è da estrarre in loop i valori che servono e ricomporre, ma direi che si può fare.

Direi pure che mentre kimono può chiudere presto, non credo lo stesso i google app script.

Sono stato lungo, sorry.

``` javascript
function doGet() {
  var feed =  UrlFetchApp.fetch('http://xkcd.com/rss.xml').getContentText();
  feed = feed.replace(
    /(&lt;img.*?alt="(.*?)".*?&gt;)/g,
    '$1' + new Array(10).join('&lt;br /&gt;') + '$2');
  return ContentService.createTextOutput(feed)
    .setMimeType(ContentService.MimeType.RSS);
}
```

**Comment by mfortini** [comment]
Ho smanettato un po' con gli app script e ho ottenuto questo feed per il mio Comune:
https://script.googleusercontent.com/macros/echo?user_content_key=u-54C14r2M4gJQ2HbBYAx2W6E99x9rsTEmULTdybr_ZeBZ5mNv6UvWip8jhbAy2B17F3ozijnykAko2gqph1iu96yRuyYvtFm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnGAZO6eUKbYaElEWgIvHPzbTKKnt1MFu1-ikZICu6t-TweI2qEYQH2omNHoRJ5oCQA4XrCmfWvkW&lib=MIc78LATZ7FQHVcnng1mNfz41BuXklfXw

**Comment by mfortini** [comment]
Ora devo scrivere la ricetta IFTTT per mandarlo su twitter/telegram e anche fare un po' di documentazione.

**Comment by aborruso** [comment]
Che gran bella notizia, mi piace.

Occhio a risolvere i problemi di validazione:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fscript.googleusercontent.com%2Fmacros%2Fecho%3Fuser_content_key%3DkkiCeFsnIEfjt-1B2-cFGC6ZYziPM8MhGoNMJ_iZjDtah4aeNFdgjSTGdUxGShLP1y0jJ6NE6_IOw23U00Cmv_IoWQ-i9p-Fm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnGAZO6eUKbYaElEWgIvHPzbTKKnt1MFu1-ikZICu6t-TweI2qEYQH2omNHoRJ5oCQA4XrCmfWvkW%26lib%3DMIc78LATZ7FQHVcnng1mNfz41BuXklfXw

Finché non sono risolti, IFTTT e molti altri non masticheranno la source.

Non vedo l'ora di vedere il codice.

Bello :)

Il giorno lun 11 gen 2016 19:50 mfortini notifications@github.com ha
scritto:

**Comment by aborruso** [comment]
@mfortini come procede con lo script? :)

**Comment by mfortini** [comment]
È pronto funziona bene ma devo riguardare la regexp che elimina gli a capo
all'interno della stessa riga di CSV perché il parser delle utility non è
in grado di gestirli.
Per il resto l'RSS che si ottiene riceve la validazione w3c a parte dei
warning, ma mi hanno dato la medaglia da apporre ;)

Il giorno gio 21 gen 2016 09:25 Andrea Borruso notifications@github.com
ha scritto:

**Comment by aborruso** [comment]
ma perché non inizi a condividerlo e magari la regexp la facciamo a più mani?

:)

**Comment by mfortini** [comment]
L'ho pushato ieri sera su master in code/ ;)

E metto le mani avanti _non_ sono un programmatore JavaScript :P

Il giorno gio 21 gen 2016 09:54 Andrea Borruso notifications@github.com
ha scritto:

**Comment by aborruso** [comment]
@mfortini mitico!!

Senza fretta e impegno, c'è fare una pagina sul wiki. Se riesco la faccio io

**Comment by aborruso** [comment]
@mfortini mi sembra quindi che l'issue lo possiamo chiudere facendo riferimento a [questo](https://github.com/aborruso/albo-pop/blob/master/code/jCityGov/RSSGen.gs)

Se sei d'accordo a te il piacere di fare click su Close

**Comment by patperu** [comment]
Ciao a tutti,
(sorry for writing in english... :/ ) 
I wrote a short R-script https://gist.github.com/patperu/4b8ef03b45632e80c5b1 to scrape 'J-City Gov' webpages. It's not fully tested, but should work. I'm still working on a R-package for albopop... 
Buona serata
Patrick

**Comment by aborruso** [comment]
wow, it's like fireworks

**Comment by mfortini** [comment]
Great news many many thanks!

Il giorno gio 21 gen 2016 17:18 Andrea Borruso notifications@github.com
ha scritto:

**Comment by mfortini** [comment]
Sto utilizzando questo progetto ora
https://github.com/mfortini/alboPretorioJCityGov

**Comment by aborruso** [comment]
@mfortini bello!!!

Perché non ci scrivi un blog post [qui](https://github.com/aborruso/albo-pop/tree/gh-pages/_posts), o su OpenDataSicilia?

E mi piacerebbe anche che lo inserissi negli [strumenti](https://github.com/aborruso/albo-pop/wiki/Strumenti).

Complimenti
