### ISSUE TITLE
Add twitter account for albopop unict

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#46]
Create an alias on google mail and a relative twitter account

**Comment by aborruso** [comment]
@cristianolongo non sono sicuro di essermi spiegato con gli alias di gmail.

Non li devi creare, ce li hai by default. Quindi per nomecognome@gmail.com hai nomecognome+albounict@gmail.com. Ogni email spedita a nomecognome+albounict@gmail.com verrà girata sempre a nomecognome@gmail.com.

Puoi quindi creare un account twitter @albounict usando come email di registrazione nomecognome+albounict@gmail.com.

Saluti

**Comment by cristianolongo** [comment]
Grazie, ora sto avendo un problema con IFTTT che nel creare canale prende sempre il primo account twitter che ho inserito ...

**Comment by aborruso** [comment]
@cristianolongo è sempre uno a uno.

Con lo stesso alias gmail, devi creare un altro account IFTTT.

**Comment by cristianolongo** [comment]
fatto grazie, l'account twitter è @albopopunict. Vediamo se funziona

**Comment by aborruso** [comment]
2016-01-09 13:09 GMT+01:00 Cristiano Longo notifications@github.com:

> fatto grazie, l'account twitter è @albopopunict. Vediamo se funziona

Se fai refresh sul sito, ho aggiunto altre PA:
http://aborruso.github.io/albo-pop/altrepa/

Se vuoi modificare il testo di unict, basta modificare questo file
https://github.com/aborruso/albo-pop/blob/gh-pages/_altrepa/unict.md e
fare il commit.

## 

Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus  http://bit.ly/GEOplus

## 38° 7' 48" N, 13° 21' 9" E, EPSG:4326

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by aborruso** [comment]
@cristianolongo hai verificato se funziona? Se sì, per favore chiudi questa issue a aggiorni [questo documento](https://github.com/aborruso/albo-pop/blob/gh-pages/_altrepa/unict.md)?

Grazie
