### ISSUE TITLE
Aggiunge AlboPOP Trabia (Problema con XPath)

### ISSUE THREAD

**Issue by matteoscire** [aborruso/albo-pop#49]
Stavo provando a fare il feed dell'Albo del Comune di Trabia. Ho provato con GDrive ma attraversi l'XPath non riesco a prendere il titolo.
https://docs.google.com/spreadsheets/d/1BB7s6kQt8A94mzzzNyrntSLcrosFYXSMGzh7mto0IB8/edit?ts=569279e4#gid=0

**Comment by ebergam** [comment]
Ciao Matteo, puoi mettere il doc pubblico? 
Comunque dai un occhio a questa estensione di chrome, a me ha aiutato molto: https://chrome.google.com/webstore/detail/xpath-helper/hgimnogjllphhhkhlmebbmlgjoejdpjl?hl=en

**Comment by matteoscire** [comment]
Documento pubblico ed estensione installata. Grazie @ebergam

**Comment by aborruso** [comment]
@ebergam ho aggiunto il tuo suggerimento in elenco qui: https://github.com/aborruso/albo-pop/wiki/Strumenti

**Comment by aborruso** [comment]
La pagina contiene [troppi errori](https://validator.w3.org/check?uri=http%3A%2F%2Fwww.comunetrabia.gov.it%2Findex.php%3Fp%3Dconsulta_albo_pretorio_tutti&charset=%28detect+automatically%29&doctype=Inline&group=0), tra cui tag non chiusi. 

In questi casi alcuni strumenti vanno in difficoltà. Sono riuscito a tirare fuori i dati (il csv del foglio "dati_da_csv"), ma ho dovuto usare strumenti più "pesanti". Per ora il mio script aggiorna quel CSV ogni 15'. Diciamo che è una buona pezza d'appoggio.

**Comment by aborruso** [comment]
Il feed RSS del comune di Trabia adesso è corretto e viene generato tramite questo script:
https://github.com/aborruso/albo-pop/blob/master/code/trabia/trabia.sh
