### ISSUE TITLE
AlboPOP Trabia, Feed non attiva il trigger

### ISSUE THREAD

**Issue by matteoscire** [aborruso/albo-pop#51]
Sul canale Telegram dell'AlboPOP non arrivano le notifiche. Questo è il feed: https://www.kimonolabs.com/api/rss/7mqzru8u?&apikey=utlI5xKmMbisI2JUNPIBuikcBOLU5I76&kimmodify=1

**Comment by grimaldi1972** [comment]
Ci sarà qualche problema sul feed, come suggerito da @aborruso non passa la validazione:
https://validator.w3.org/feed/

**Comment by aborruso** [comment]
@matteoscire verifica la funzione javascript, nella parte relativa al link.

Dovrebbe essere cosa di due minuti

**Comment by matteoscire** [comment]
Sì, il problema era nel feed perchè i link degli avvisi aprivano finestre "about blank". il problema risiedeva nel fatto che dentro "title" non c'era "href". Abbiamo dovuto applicare questa funzione per risolvere il problema:
var newtitle = {
    "href": data.results.collection1[key].href,
    "text": data.results.collection1[key].title 
    }
    data.results.collection1[key].title = newtitle;  
  }
