### ISSUE TITLE
Consigliare nella wiki di controllare le api di Kimono

### ISSUE THREAD

**Issue by ebergam** [aborruso/albo-pop#52]
Mi sono accorto che kimono ogni tanto si può "inceppare". Su Bondeno non pubblicava da 5 giorni e si era bloccato nello stato di "crawling in progress". Basta fare stop e riparti come soluzione short-term.
E long-term? Abbandonare kimono e scripting direi? :)

**Comment by aborruso** [comment]
@ebergam abbiamo pronto un po' di script generici, autoconsistenti. 

Ce ne sono in Python, in R, in PHP e in bash.

A breve dobbiamo migrare tutto. Metterei la nota che dici nel wiki.

Grazie
