### ISSUE TITLE
JCityGov: regexp eliminazione a-capo in CSV non funziona in tutti i casi

### ISSUE THREAD

**Issue by mfortini** [aborruso/albo-pop#57]
Se si usa ad esempio l'albo pretorio di Pisa, a volte non vengono eliminati tutti gli a-capo nel CSV e non si riesce ad ottenere RSS

http://albopretorio.comune.pisa.it/web/trasparenza/albo-pretorio

**Comment by aborruso** [comment]
@mfortini questa è chiudibile? Immagino tu l'abbia già superata.

Se sì, accenni come?

grazie

**Comment by mfortini** [comment]
Il CSV degli albi JCityGov non è completo, in quanto mancano i permalink al dettaglio della notizia. Si è scelto di utilizzare delle query XPath per ricavare i dati dalla pagina e quindi elaborarli direttamente nel foglio dello spreadsheet.
