### ISSUE TITLE
Google script di creazione RSS da CSV: link invariati?

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#59]
@mfortini ha creato un comodissimo e utile script javascript, da usare in [google script](script.google.com) per convertire a runtime una source in formato CSV in RSS.

Lo script è [questo](https://github.com/aborruso/albo-pop/blob/master/code/jCityGov/RSSGen.gs) e lo potete testare usando questo URL:

[https://script.google.com/macros/s/AKfycbyNi8sYYkXmgyEw7txj3hwavYZNkVoU3L2KXoI2F6BwdY_AhJSL/exec](https://script.google.com/macros/s/AKfycbyNi8sYYkXmgyEw7txj3hwavYZNkVoU3L2KXoI2F6BwdY_AhJSL/exec)

Nell'XML di output i link puntano sempre a  http://servizi.comune.cento.fe.it/web/trasparenza/albo-pretorio, mentre l'ideale sarebbe che puntassero alla pagina di dettaglio dell'item che hanno una struttura di questo tipo:

[http://servizi.comune.cento.fe.it/web/trasparenza/albo-pretorio/-/papca/display/191](http://servizi.comune.cento.fe.it/web/trasparenza/albo-pretorio/-/papca/display/191)

Ora che c'è il codice, si può provare un po' tutti a modificarlo e ottimizzare la cosa.

**Comment by mfortini** [comment]
Confermo:
il link sarebbe da correggere, per ora purtroppo non ho trovato 
riferimenti nel CSV al numero da inserire nell'URL dopo display.

Farò una versione anche con scrapy o simili, la cosa interessante del 
CSV è che è molto veloce ottenere una lista dei contenuti dell'albo: per 
il comune di Pisa per esempio si ottiene un CSV con più di 10000 righe!

Grazie per tutti i contributi!

Il 21/01/2016 16:17, Andrea Borruso ha scritto:

**Comment by aborruso** [comment]
@mfortini potresti usare [questo CSV](http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CE&key=1m4X9WFhxqyUZWP6WIpLJf4CLoRmzCjpkOMzsE6U-3zw), generato dinamicamente tramite XPATH in [questo foglio](https://docs.google.com/spreadsheets/d/1m4X9WFhxqyUZWP6WIpLJf4CLoRmzCjpkOMzsE6U-3zw/edit?usp=sharing).

Nella prima riga trovi i riferimenti XPATH

**Comment by aborruso** [comment]
E lo script si potrebbe inserire nello stesso sheet

**Comment by aborruso** [comment]
@mfortini questo si può chiudere?

**Comment by mfortini** [comment]
Aggiunta una colonna che seleziona solo la parte utile con una semplice regexp
