### ISSUE TITLE
Aggiornamento Albo Pop SGJ - Estendere campo di notifica

### ISSUE THREAD

**Issue by giuragu** [aborruso/albo-pop#6]
Al momento l'Albo Pretorio di San Giuseppe Jato è tale per cui le notifiche si riferiscono a quanto pubblicato in prima pagina (n°7). Pertanto in caso di simultanea pubblicazione di un numero maggiore di atti alcune notifiche non vengono inviate.

Proposta 1: estendere almeno alle prime due pagine il campo di notifica per avvenuta pubblicazione
Proposta 2: fare in qualche modo riferimento alla data di pubblicazione nel sistema che gestisce il "prelievo" dell'informazione sulla pubblicazione avvenuta. Prevedendo la ricerca nell'intero albo.

**Comment by aborruso** [comment]
@giuragu84 si può fare, ma c'è da scrivere del codice. Quindi non è immediato, ma verrà fatto e poi potrà essere riutilizzato per altri comuni.

**Comment by giuragu84** [comment]
ok. avevo infatti appena verificato che il problema è anche su bagheria dove però il numero max è 10.
lì vedo che proprio ieri si è verificato il caso

**Comment by giuragu** [comment]
@aborruso ho chiuso per errore. Volevo dirti.... ok, avevo infatti appena verificato che il problema è anche su bagheria dove però il numero max è 10. lì vedo che proprio ieri si è verificato il caso

P.S.: Si può riaprire l'issue?

**Comment by aborruso** [comment]
L'ho riaperto, perché è da migliorare. Grazie @giuragu84

**Comment by giuragu** [comment]
@aborruso Nell'attesa che si possa risolvere "via codice", qualora si presentasse il problema per san giuseppe jato e qualora non si sia risolto prima del lancio, potrei vedere di fare una forzatura inviando le eventuali notifiche "sfuggite" manualmente,...che ne pensi? Vorrei che non ci siano dubbi sulla validità piena del sistema...

**Comment by aborruso** [comment]
@giuragu84 ti ho reso amministratore del canale Telegram. Ma spero di chiudere diversemente la cosa nelle prossime settimane :)

**Comment by giuragu** [comment]
@aborruso ok perfect ;)
