### ISSUE TITLE
ciao e aggiungere Matera e Potenza

### ISSUE THREAD

**Issue by piersoft** [aborruso/albo-pop#60]
Ciao ragazzi. io sto usando soluzioni miste tra Kimonolab, script google e Zapier (che mi sta risolvendo un sacco di rogne).
ovvio che partendo da un xpath su gdrive si agevola di molto tutto.
oltre Lecce, sto finendo Matera, Potenza e testando Brindisi, Surbo, Galatina e Tricase.
Appena sono pronti li aggiungo in coda. Intanto:

Matera (albo e news): 
Twitter @alpopopmatera
Ch.Telegram @comunedimaterachannel (albo e news)

Potenza 
Twitter @albopoppotenza 
Ch. Telegram @ComunePZ (albo e news)

Galatina:
Ch. Telegram @comunedigalatinanews 

Tricase:
Ch. Telegram @comunetricase   

Brindisi
Ch. Telegram @albopopbrindisi 

Per Matera e Potenza ho messo il profilo Twitter secondo lo schema Pop.

**Comment by aborruso** [comment]
@piersoft quando hai tempo, perché non aggiungi una pagina wiki su Zapier? 

Così arricchiamo la pagina sugli [strumenti](https://github.com/aborruso/albo-pop/wiki/Strumenti).

Grazie

**Comment by aborruso** [comment]
Aggiunte Matera e Potenza http://aborruso.github.io/albo-pop/comune/

**Comment by aborruso** [comment]
@piersoft ma l'account twitter alpopopmatera non esiste. Qual è quello corretto?
