### ISSUE TITLE
Aggiungere Agira (Sicilia)

### ISSUE THREAD

**Issue by etanoox** [aborruso/albo-pop#62]
La pagina dell'albo pretorio del Comune di Agira è questa: www.comuneagira.gov.it/albo-pretorio.html

Adesso puoi seguire le nuove pubblicazioni in albo in tre modi dedicati:

su un account Twitter https://twitter.com/albopop_agira;
su un canale Telegram https://telegram.me/albopretorioagira;
su una pagina Facebook https://www.facebook.com/albopopAgira

**Comment by aborruso** [comment]
Benvenuto e complimenti!

**Comment by etanoox** [comment]
Grazie mille :)

**Comment by aborruso** [comment]
Eccolo http://aborruso.github.io/albo-pop/comune/agira.html :)
