### ISSUE TITLE
Problema creazione feed RSS Comune di Nissoria (Sicilia)

### ISSUE THREAD

**Issue by etanoox** [aborruso/albo-pop#63]
Salve, come da oggetto, sto riscontrando dei problemi nella creazione del feed RSS per l'albo pretorio del Comune di Nissoria ( link:  http://pubblicazioni.saga.it/publishing/AP/index.do?org=nissoria )
Seguendo la videoguida di Kimono, creo la prima table "title" e poi la seconda "pubDate"; 
modifico da kimono la data di pubblicazione per renderla standard RSS;
A questo punto, quando vado ad inserire il link del nuovo RSS su IFTTT per creare la nuova ricetta, il sistema mi da l'errore: "  Feed has items without valid urls " 

Facendo svariati tentativi ho capito che c'è un problema nella creazione del feed RSS, più specificatamente il Feed non riesce a trovare l'URL per ogni "title".

Chiedo aiuto a tutti voi

**Comment by etanoox** [comment]
![schermata 2016-01-25 alle 12 05 17](https://cloud.githubusercontent.com/assets/1361082/12550721/e4268726-c365-11e5-988e-4024e6cfeb44.png)

**Comment by etanoox** [comment]
Come si vede dallo screenshot, credo che il problema è il seguente:
kimono non "cattura"  il riferimento   href="" e per questo successivamente ritroveremo quell'errore, creando la ricetta IFTTT.
La domanda specifica è quindi: come creare un feed RSS corretto?

**Comment by gcardaci** [comment]
Ciao Giuseppe,
benvenuto, sono contento anche perché siamo quasi vicini di casa (io
Leonforte), ed abbiamo frequentato lo stesso liceo.
anche io avevo tentato di iniziare l'albo di Nissoria, giusto per allenarmi
e fare un regalo ad Armando Glorioso, con feed43 ero riuscito ad estrarre
un buon rss poi ho tralasciato ma se vuoi possiamo riprendere il filo.

Il lunedì 25 gennaio 2016, etanoox notifications@github.com ha scritto:

**Comment by etanoox** [comment]
Ciao Giuseppe, bello ritrovarsi sul web :)
Purtroppo non conosco feed43 e per questo avevo provato con Kimono, magari portando avanti la stessa procedura usata per quello di Agira.
Comunque si, se ti va possiamo andare avanti....

**Comment by aborruso** [comment]
@etanoox  come hai risolto?

**Comment by etanoox** [comment]
Non ho risolto. Conto di sentirmi con @gcardaci in privato e lavorarci insieme. 
Nel frattempo sto cercando di creare gli altri della mia provincia.
