### ISSUE TITLE
AlboPopPisa

### ISSUE THREAD

**Issue by mfortini** [aborruso/albo-pop#65]
Ho aperto https://twitter.com/alboPOPPisa
Viene caricato da Zapier tramite un google apps script che genera l'RSS partendo da un Google sheet che mi ha condiviso @aborruso per riempire una tabella con le giuste query XPath dagli albi JCityGov di Maggioli

**Comment by aborruso** [comment]
Bello @mfortini !!!

Appena puoi lo aggiungi in lista? Qui la guida [https://github.com/aborruso/albo-pop/wiki/Come-aggiungere-un-Comune-alla-lista](https://github.com/aborruso/albo-pop/wiki/Come-aggiungere-un-Comune-alla-lista)

Grazie

**Comment by mfortini** [comment]
Fatto!

**Comment by mfortini** [comment]
le IMPORTXML sul google doc restituiscono dei valori doppi: qualcuno sa dirmi perché? Ho provato ad usare la query xpath da chrome e i valori sono corretti

**Comment by aborruso** [comment]
I duplicati sono in origine l'importXML è ok. La richiudo
