### ISSUE TITLE
Aggiungere Gagliano Castelferrato (Sicilia)

### ISSUE THREAD

**Issue by etanoox** [aborruso/albo-pop#68]
Salve, ho questo feed RSS creato con kimono (Comune di Gagliano)
https://www.kimonolabs.com/api/rss/dek02czo?&apikey=1v2cs9NIll2HWnengFCSh4TnW0cfPsLy&kimmodify=1

Ho applicato le modifiche riportate nel wiki ovvero:
- la data di pubblicazione per renderla standard RSS;
- l'URL encoding agli URL, per essere compliant con Telegram

La mia domanda è: va modificato nell'url anche il carattere ? (punto interrogativo)

**Comment by aborruso** [comment]
@etanoox ho testato il tuo feed RSS ed è compliant con Telegram, complimenti!

Per tutto il resto (twitter, facebook, ...) non devi fare le modifiche di URL encoding. Puoi clonare questa API di kimono, modificarla di conseguenza e usarla per gli altri canali.

**Comment by etanoox** [comment]
Perfetto. Non chiudo ancora così appena ho tutto pronto incollo qui i riferimenti con i vari link a fb, telegram ecc?

**Comment by etanoox** [comment]
La pagina dell'albo pretorio del Comune di Gagliano Castelferrato è questa: http://www.comunegaglianocastelferrato.gov.it/albo-pretorio

Adesso puoi seguire le nuove pubblicazioni in albo in tre modi dedicati:

su un account Twitter https://twitter.com/AlboPopGagliano;
su un canale Telegram https://telegram.me/albopopgagliano;
su una pagina Facebook https://www.facebook.com/albopopgagliano;

Autore: Giuseppe Ricceri

**Comment by aborruso** [comment]
Fatto[http://aborruso.github.io/albo-pop/comune/gaglianocastelferrato/](http://aborruso.github.io/albo-pop/comune/gaglianocastelferrato/)

Qual è l'URL del feed RSS?

**Comment by etanoox** [comment]
Eccolo
https://www.kimonolabs.com/api/rss/asjp1aio?&apikey=xdrzwHHqmGGVGLJou3rIRytAaCunz8e6&kimmodify=1
