### ISSUE TITLE
Albo POP anche a Torre Santa Susanna (Brindisi)

### ISSUE THREAD

**Issue by simoneversienti** [aborruso/albo-pop#70]
Buongiorno a tutti e complimenti per l'ottimo lavoro che avete messo in piedi.
Mi presento, sono Simone Versienti, 19 anni ed abito a Torre Santa Susanna, un paese di 10.000 abitanti in provincia di Brindisi.
Vi spiego brevemente perchè sono qui: qualche giorno fa, nel mio paese hanno cambiato i sensi di marcia di alcune vie e l'unica comunicazione è stata data, giustamente, sull'Albo Pretorio del Comune (accessibile a [quest'indirizzo](http://dgegovpa.it/TorreSantaSusanna/Albo/Albo.aspx)).
Per caso mi sono imbattuto in un post condiviso originariamente da Piersoft Paolicelli e ri-condiviso da Salvatore Longo.
C'ho cliccato ed ho subito pensato "Ma guarda un po'! Proprio quello che servirebbe nel mio Comune!"
La prima cosa che ho fatto è contattare Andrea e chiedere qualche delucidazione in merito. 
Il primo passo sarebbe fare una richiesta formale al Comune; se questo non dovesse mostrarsi interessato, allora sceglieremo una via alternativa.
Aspetto vostri consigli, buona giornata!

**Comment by aborruso** [comment]
Benvenuto @simoneversienti 
Per ora di corsa e senza troppe spiegazioni e solo con una cosa un po' più tecnica.

I dati dalla pagina dell'albo si possono estrarre facilmente con XPath. In [questo](https://docs.google.com/spreadsheets/d/1uX0KI1A3oGQNHtVcgWKAQdjvli4OUtMswURwIetDV7o/edit?usp=sharing) foglio l'estrazione è automatica a partire dalla pagina sorgente.

Non sono tutte rose e fiori. Vai a pagina 2 o pagina 3 dell'albo. Noterai che l'indirizzo è uguale a quello di pagina 1. Quindi non c'è un modo diretto di fare l'estrazione della pagine diverse da 1, perché tutte hanno lo stesso indirizzo. E' risolvibile, ma c'è da lavorarci.

Per il momento mi fermo qui.

**Comment by simoneversienti** [comment]
Cosa mi consigli di fare nel frattempo? Presentare richiesta al Comune? Se esiste un modulo già preparato, potresti inviarmelo?

**Comment by etanoox** [comment]
Ciao @simoneversienti  dal wiki ti incollo quanto segue:

Modello di "Proposta di condivisione e promozione del progetto Albo POP"

(Destinatario: Pubblica Amministrazione)

[https://docs.google.com/document/d/1kbtg80HmLzKJjWmual9Wm92Gu41bNcy_Pu3GiTkbtGA/edit?ts=564b5e1c](url)

**Comment by giuragu** [comment]
Ciao @simoneversienti io ho proprio utilizzato quel modello che ti ha segnalato @etanoox . Fa riferimento a dei canali già funzionanti che l'amministrazione può promuovere e condividere. L'iter che ho seguito a San Giuseppe jato (PA), mio comune, è stato proprio questo: canali prima creati, poi testati e poi proposti al comune con quel modulo per la condivisione  e promozione.

**Comment by simoneversienti** [comment]
Purtroppo non funziona il link. Sapete il motivo?

**Comment by giuragu** [comment]
@simoneversienti se vai da sezione Wiki/Documenti utili cioè qui [(https://github.com/aborruso/albo-pop/wiki/Documenti-utili-(modelli,-ecc...)] lo trovi. Da lì ti si dovrebbe aprire senza problemi

**Comment by simoneversienti** [comment]
@aborruso però, prima di consegnare la richiesta al Comune, dovremmo trovare una soluzione al fatto che l'albo di Torre Santa Susanna, anche scorrendo le pagine, non cambia il suo indirizzo. Ti ricordi che ne parlammo?

**Comment by aborruso** [comment]
@simoneversienti non è risolvibile rapidamente dall'esterno, ma possiamo pensare a una verifica di nuovi elementi ogni 15' nella prima pagina. Secondo me nel 99% dei casi non perderemo nulla.

Se pensi che possa andare bene, mi metto a lavorarci.

**Comment by simoneversienti** [comment]
Si, va benissimo. Fammi sapere non appena avrai sviluppato qualcosa, grazie :+1:

**Comment by aborruso** [comment]
@simoneversienti  ecco il feed RSS che si aggiornerà in automatico:

[http://feeds.feedburner.com/AlboPretorioComuneTorreSantaSusanna](http://feeds.feedburner.com/AlboPretorioComuneTorreSantaSusanna)

Adesso con questo puoi creare l'automazione per la pubblicazione su [Telegram](https://github.com/aborruso/albo-pop/wiki/IFTTT#pubblicare-gli-aggiornamenti-di-un-feed-rss-su-un-canale-telegram), Twitter, ecc.

Saluti

**Comment by simoneversienti** [comment]
Grazie mille Andrea, davvero!

**Comment by simoneversienti** [comment]
Andrea ho un problema con il Feed RSS: il titolo non corrisponde a quello pubblicato sull'Albo oppure, se è corretto, non è collegato al file .pdf giusto.

**Comment by piersoft** [comment]
se avete bisogno fate un fischio

Il giorno 16 febbraio 2016 14:32, simoneversienti notifications@github.com
ha scritto:

**Comment by aborruso** [comment]
@simoneversienti era uno strano fatto momentaneo, ora sembra ok [http://feeds.feedburner.com/AlboPretorioComuneTorreSantaSusanna](http://feeds.feedburner.com/AlboPretorioComuneTorreSantaSusanna)

**Comment by simoneversienti** [comment]
Ok perfetto, grazie
