### ISSUE TITLE
RSS comune di Prato

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#72]
Caro Matteo, c'è un feed RSS per Prato?

Se sì, lo metti nella pagina web pubblica di anagrafica?

Se non c'è, lo creerei, perché è molto abilitante e consente a chiunque di farci altro.

Grazie

**Comment by mfortini** [comment]
@aborruso il file te lo preparo in fretta, dove lo hostiamo?

**Comment by aborruso** [comment]
On 1 February 2016 at 11:36, mfortini notifications@github.com wrote:

> @aborruso https://github.com/aborruso il file te lo preparo in fretta,
> dove lo hostiamo?

Dove vuoi tu. Io ho un server dove posso mettere il tuo script.
E' Python?

## 

Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus  http://bit.ly/GEOplus

## 38° 7' 48" N, 13° 21' 9" E, EPSG:4326

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by mfortini** [comment]
Ho appena caricato il codice qui https://github.com/aborruso/albo-pop/tree/master/code/prato per ora gira su una mia macchina, se vuoi spostarlo dimmi pure, altrimenti genero RSS e lo carico sul mio server o da qualche altra parte

**Comment by aborruso** [comment]
Se hai un tuo spazio allora, per il momento, preferisco che lo gestisca tu.

Rimango allora in attesa di un URL.

Grazie

Il giorno lun 1 feb 2016 11:43 mfortini notifications@github.com ha
scritto:

**Comment by mfortini** [comment]
Primo tentativo di feed RSS (valida con qualche raccomandazione, ma mi darebbe la medaglietta) http://opendata.matteofortini.it/alboPOPPrato.xml

**Comment by aborruso** [comment]
Mi pare perfetto chiudo la issue. Appena puoi inseriscilo nella pagina.

Grazie
