### ISSUE TITLE
RSS Comune di Lizzanello

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#73]
Ciao @piersoft, inserisci per favore anche il feed RSS nella [scheda anagrafica](https://github.com/aborruso/albo-pop/blob/gh-pages/_comune/lizzanello.md) di Lizzanello?

Grazie

**Comment by piersoft** [comment]
Non c'è. Fa scraping su google sheet. 

Inviato da iPhone

**Comment by aborruso** [comment]
mi condividi qui l'URL al solo CSV generato da gsheet? Grazie e senza fretta

**Comment by piersoft** [comment]
https://docs.google.com/spreadsheets/d/1USN0msBtfroCIfZh5P0pWFFRzpg7ZI-fCw05dXAKRnk/pub?gid=0&single=true&output=csv

Il giorno 1 febbraio 2016 20:10, Andrea Borruso notifications@github.com
ha scritto:

**Comment by aborruso** [comment]
Grazie, adesso tocca a me ;)

**Comment by piersoft** [comment]
https://www.kimonolabs.com/api/rss/2v9297e6?&apikey=EcELyNfS6DRZHFvOVmQ6Uems266NeXdB&kimmodify=1

2016-02-01 23:48 GMT+01:00 Andrea Borruso notifications@github.com:

**Comment by aborruso** [comment]
@piersoft gli URL del feed sono da correggere.

Al momento sono così

```
http://www.comune.lizzanello.le.it/lizzanello/mc/mc_p_dettaglio.php%3Fid_pubbl=6432
```

E si ottiene
![2016-02-02_09h57_00](https://cloud.githubusercontent.com/assets/30607/12744346/fb387efe-c993-11e5-93d3-286b372bcaea.png)

Mentre devono essere 

```
http://www.comune.lizzanello.le.it/lizzanello/mc/mc_p_dettaglio.php?id_pubbl=6432
```

**Comment by piersoft** [comment]
che nervi ho applicato la correzione e mi ha cancellato tutto il lavoro di
normalizzazione precedente..

10 minuti e riaggiusto href title pubdate e & e =

:(

Il giorno 2 febbraio 2016 10:02, Andrea Borruso notifications@github.com
ha scritto:

**Comment by piersoft** [comment]
https://www.kimonolabs.com/api/rss/2v9297e6?&apikey=EcELyNfS6DRZHFvOVmQ6Uems266NeXdB&kimmodify=1

Il giorno 2 febbraio 2016 10:24, Francesco Piero Paolicelli <
piersoft2@gmail.com> ha scritto:

**Comment by aborruso** [comment]
Grazie mille @piersoft per http://feeds.feedburner.com/Albopoplizzanello
