### ISSUE TITLE
RSS Comune di Troina

### ISSUE THREAD

**Issue by etanoox** [aborruso/albo-pop#75]
Salve a tutti,
volevo chiedere se qualcuno ha esperienza con un albo che crea un cookie di sessione.
L'albo in questione è:
http://amministrazionetrasparente.comune.troina.en.it/web/trasparenza/atti-amministrativi;jsessionid=5C015FAE801A21A919E0497EDF0F1799

Qualcuno conosce la procedura per creare un feed rss per casi come questo?

**Comment by aborruso** [comment]
ciao @etanoox i dati si possono estrarre. Puoi partire da 

[https://docs.google.com/spreadsheets/d/12WlGtZiEUrWSm1sNJeOROzcEJVZJEBO2UG6myC1N_gk/edit?usp=sharing](https://docs.google.com/spreadsheets/d/12WlGtZiEUrWSm1sNJeOROzcEJVZJEBO2UG6myC1N_gk/edit?usp=sharing)
