### ISSUE TITLE
Creata rassegna stampa

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#81]
Buon pomeriggio,
visto il numero di articoli sull'AlboPOP era necessario creare una rassegna stampa:
- [full screen](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1ceZXZEYkvExfbxPxipYipb-5FDrqA-Yh9QYlFaMsV4o&font=Default&lang=it&hash_bookmark=true&initial_zoom=2&height=650#event-rassegna-albopop);
- in una [pagina](http://aborruso.github.io/albo-pop/rassegnastampa/) del sito;
- il [foglio](https://docs.google.com/spreadsheets/d/1ceZXZEYkvExfbxPxipYipb-5FDrqA-Yh9QYlFaMsV4o/edit?usp=sharing) sorgente.

Se volete dare una mano, fatemi un fischio e vi aggiungo in modifica sul foglio.

Grazie a tutti

**Comment by giuragu** [comment]
@aborruso idea ottima! comunque la rassegna stampa non ha ancora un link nel menu principale in alto a destra giusto?

**Comment by aborruso** [comment]
On 9 February 2016 at 11:08, giuragu84 notifications@github.com wrote:

> @aborruso https://github.com/aborruso idea ottima! comunque la rassegna
> stampa non ha ancora un link nel menu principale in alto a destra giusto?

giusto, ci sarebbe un po' da lavorare sul sito :)

## 

 Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

## 

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino
