### ISSUE TITLE
Albopop Comune di Capaci

### ISSUE THREAD

**Issue by grimaldi1972** [aborruso/albo-pop#82]
Anche l'albo del comune di Capaci è protetto da cookie (credo):

http://89.97.237.87/publishing/AP/index.do;jsessionid=B6147695ABDAADA711E1B37A9C1FC85C

ho cercato di seguire la https://github.com/aborruso/albo-pop/issues/61
ma mi sono perso.

Con kimonolabs ho creato questo rss
https://www.kimonolabs.com/api/rss/cldllo7q?apikey=j1EDoR5py5DQK6R76jt85wU1zCMzTrdS

**Comment by aborruso** [comment]
@grimaldi1972 è protetto da cookie di sessione.

Se non hai navigato nel sito, infatti da questo

http://89.97.237.87/publishing/AP/docDetail.do?docId=7291

ottieni :(

![2016-02-09_09h24_10](https://cloud.githubusercontent.com/assets/30607/12910922/e92d7dec-cf0e-11e5-9de5-23fe9b8e70d3.png)

**Comment by grimaldi1972** [comment]
Quindi lo 'bypassiamo'...?

**Comment by antocalderone** [comment]
Ho lo stesso identico problema con l'albo del comune di Termini Imerese. Come risolvere il problema dei cookie di sessione?

**Comment by aborruso** [comment]
@antocalderone ti ho risposto in una issue dedicata #84
