### ISSUE TITLE
Kimonolabs chiude

### ISSUE THREAD

**Issue by piersoft** [aborruso/albo-pop#85]
https://www.kimonolabs.com/ sta chiudendo il 29.02

dobbiamo fare velocemente le migrazioni degli albopops , non credete?

**Comment by aborruso** [comment]
Sì sì.
Usiamo questo thread per raccogliere gli albi basati su Kimono.

Poi io, @mfortini e @iltempe abbiamo fatto degli script che potremmo usare all'occorrenza

**Comment by piersoft** [comment]
cavolo a me sono tanti. o perchè direttamente pescano sul sito degli albi oppure perchè rilavorano il google sheet html..

Bari
Matera
Latiano
oria
Lizzanello
Trieste
Surbo
Tricase
Lecce

**Comment by aborruso** [comment]
@piersoft i fogli google sheet, non sono un problema e li possiamo riusare come source.

Usiamo questo [sheet](https://docs.google.com/spreadsheets/d/1G4y-FgdyYeCW2QGNzUT9XxnHEg4rNhevjJVHcmT2tk0/edit?usp=sharing) per costruire un'anagrafica (senza fretta)

**Comment by mfortini** [comment]
Penso che da un foglio google sheet siccome viene fuori anche un CSV fare
un RSS sia una fischiata, il problema al massimo è dove mettere il feed: io
ho fatto una sottodirectory sul mio server non indicizzata che si può
utilizzare, ma se avere posti migliori possiamo organizzarci.

Mannaggia kimono era un gran bel tool!

Il giorno mar 16 feb 2016 09:39 Andrea Borruso notifications@github.com
ha scritto:

**Comment by aborruso** [comment]
@mfortini visto lo script che hai già creato, ti faccio una richiesta (senza impegno).

A partire da uno sheet modello, che contiene tre colonne `title`,`pubDate` e `link`, scrivere lo script (embeddato nello sheet) che genera il feed RSS a partire dal foglio.

In questo modo, anche a livello di strumento riusciremo a rimanere POP, che è un elemento molto importante e fondante; basterà infatti moltissimi casi imparare a fare una query XPath con gsheet e quasi chiunque potrà crearsi il suo.

Che ne pensi?

**Comment by mfortini** [comment]
Mi sembra un'ottima idea!

Il 16/02/2016 09:55, Andrea Borruso ha scritto:

**Comment by aborruso** [comment]
2016-02-16 10:07 GMT+01:00 mfortini notifications@github.com:

> Mi sembra un'ottima idea!

Ti voglio bene!

## 

 Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

## 

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by sabas** [comment]
Usare morph.io? https://morph.io/

(nell'api c'è anche il formato atom che va bene per gli rss)

**Comment by duemme** [comment]
Io avevo creato un'API con Kimonolabs per l'albo pretorio del comune di Bordighera. Vorrei continuare a poter raccogliere i dati su base giornaliera e visualizzarli mediante lettore rss.

**Comment by eccoilmoro** [comment]
Io per Bassa Romagna uso morph.io
Funziona bene,  può però schedulare una sola esecuzione al giorno.

Sorry for typos, sent from mobile

Usare morph.io? https://morph.io/

**Comment by iltempe** [comment]
La mia soluzione è tutta in PHP. Devo sistemare solo una cosa penso di chiudere in serata.

Quoto la soluzione di andrea di creare un livello per disaccoppiare il parsing dalla generazione del feed mi piace.

Matteo

**Comment by aborruso** [comment]
Grazie allo script di @mfortini (vedi #89) riusciremo a salvare tutti gli albi.

Per darvi un'idea @piersoft ha già migrato i tanti suoi albiPOP. Quindi SI PUO' FARE :)

Ricordo a tutti gli orfani di kimono, di comilare [questo foglio](https://docs.google.com/spreadsheets/d/1G4y-FgdyYeCW2QGNzUT9XxnHEg4rNhevjJVHcmT2tk0/edit#gid=0).

**Comment by duemme** [comment]
Ho aggiunto al file excel il link al feed rss che avevo creato con Kimonolabs per monitorare l'albo pretorio del Comune di Bordighera.

**Comment by aborruso** [comment]
ciao @duemme con lo [script](https://github.com/aborruso/albo-pop/tree/master/code/GDriveGeneric) di @mfortini è cosa semplice "salvare" un albo come quello di Bordighera.

Stiamo iniziando a documentare il processo, ma è ancora incompleto. Una prima versione di how-to è [qui](https://github.com/aborruso/albo-pop/tree/master/code/GDriveGeneric/tutorial_ita).

Ho già creato il nuovo feed RSS che trovi qui [https://script.google.com/macros/s/AKfycbynDKPbGyiW18GCTYgiyjA82N1ifROCB-JP4wGU1FiOTSv-SPA/exec](https://script.google.com/macros/s/AKfycbynDKPbGyiW18GCTYgiyjA82N1ifROCB-JP4wGU1FiOTSv-SPA/exec)

Come [vedi](https://validator.w3.org/feed/check.cgi?url=https%3A//script.google.com/macros/s/AKfycbynDKPbGyiW18GCTYgiyjA82N1ifROCB-JP4wGU1FiOTSv-SPA/exec), sorpassa la validazione.

La sorgente del feed è [questo foglio](https://docs.google.com/spreadsheets/d/1zMw5JRyVtdUUrvacsaa6FMySisXINvJUh7wxZyIyK4U/edit?usp=sharing) che ho condiviso in scrittura con te.

Saluti

**Comment by duemme** [comment]
Ottimo lavoro!
Appena ho due secondi leggo l'how-to, anche se per uno di formazione
giuridica come me, non è semplicissimo addentrarmi in questioni tecniche.
Amavo Kimonolabs proprio per la semplicità di utilizzo.
A presto e grazie ancora.
Matteo

2016-02-29 10:07 GMT+01:00 Andrea Borruso notifications@github.com:

**Comment by aborruso** [comment]
@duemme possiamo aggiungere Bordighera in [lista](http://aborruso.github.io/albo-pop/comune/)?

Come usavi il feed da kimono? Solo per un RSS o per altri output come Telegram? Ci scrivi eventualmente i dettagli per raggiungere gli altri output?

**Comment by duemme** [comment]
@aborruso puoi aggiungerlo senz'altro alla lista.
Usavo il feed da Kimono attraverso il plugin di chrome per leggere i feed RSS e ogni volta che il feed si aggiornava controllavo le nuove pubblicazioni dell'albo per verificare se vi fosse qualcosa di interessante. Non ho predisposto altri output.
