### ISSUE TITLE
Una gran bella notizia (non la fate ancora girare)

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#88]
Inizio con questo messaggio, una serie che di comunicazioni. Parto dalla più bella e faccio parlare un'immagine:

![2016-02-24_18h36_08](https://cloud.githubusercontent.com/assets/30607/13294701/84ebc1b8-db25-11e5-856d-8bc196458437.png)

Questa mattina all'alba il comune di **San Giuseppe Jato** ha formalizzato il suo sostegno ufficiale al nostro progetto. Tutto questo si deve a @giuragu84 che si è speso per fare qualcosa di utile per la sua comunità, con generosità e sopratutto qualità. A lui va il mio ringraziamento e la mia stima.

Vi prego di **non fare girare la cosa**, perché è giusto che sia lui a darne per primo notizia. [Questa](http://156.54.128.62/sgjato/mc/mc_p_dettaglio.php?id_pubbl=1614) la notizia in albo.

Con l'occasione prepareremo una pagina "come si usa l'alboPOP"" per il sito web del comune San Giuseppe Jato, che potrà essere usata per tutte le occasioni simili, formali e informali.

Saluti

**Comment by mfortini** [comment]
I miei complimenti, sono notizie che riempiono di gioia

Il giorno mer 24 feb 2016 18:42 Andrea Borruso notifications@github.com
ha scritto:

**Comment by cirospat** [comment]
figataaaaa

Il giorno 24 febbraio 2016 18:45, mfortini notifications@github.com ha
scritto:

**Comment by ebergam** [comment]
Ma tanta roba! Mitico @giuragu84 ! :)

**Comment by iltempe** [comment]
Commozione massima. Complimentoni.

Matteo T.

**Comment by giuragu** [comment]
Grazie @aborruso per aver dato qui questa bella notizia. Si è proprio una figata, è una roba incredibile e riempie anche me di emozione, di commozione e di gioia. 
Grazie a tutti per la vostra condivisione senza la quale non sarebbe possibile nulla di tutto ciò. 
Credo fermamente in questo progetto perché offre conoscenza e consapevolezza diffusa seminando possibile inclusione sociale.

Sto preparando due righe sulla notizia....dopodiché vi avviserò per dare fiato alle trombe :)

Giuseppe Ragusa

**Comment by gcardaci** [comment]
E' bello!!

Il giorno 25 febbraio 2016 09:01, giuragu84 notifications@github.com ha
scritto:

**Comment by giuragu** [comment]
Ve lo avevo promesso.
Ne scriviamo qui con @aborruso: 
http://aborruso.github.io/albo-pop/Albo-POP-condiviso-e-promosso-dal-Comune-di-San-Giuseppe-Jato/
