### ISSUE TITLE
Nuova modalità POP per generare albi POP

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#89]
Il problema principale della chiusura di kimono non è l'impossibilità di creare un feed RSS, ma quello di rendere meno immediato il farlo a chiunque.

Ma per fortuna, tra le cose più importanti di questo progetto c'è quella di avere **fatto rete** e in questa rete c'è @mfortini. Ebbene Matteo ha reso possibile la creazione di un **feed RSS** a partire da uno *_spreadsheet *_di google drive. In buona sostanza:
- si crea un nuovo foglio elettronico;
- si importa un albo tramite `importxml` e `XPATH` (molti che non ne avevano mai sentito parlare, hanno imparato a farlo qui dentro);
- si applica uno script al foglio, facendo essenzialmente un copia e incolla.

Creato il feed, abbiamo l'albo POP.

Prego @mfortini di fare una miniguida sul wiki (poi vorrei fare blog post e darne molta molta diffusione) in modo che a tutti quelli che chiederanno come fare un alboPOP, senza avere grandi conoscenze, potremmo segnalare questa pagina di help.

Grazie mille a Matteo, per questa cosa importante e che stimolerà mille altre usi oltre all'alboPOP

**Comment by cirospat** [comment]
questo mi piace molto.
Mi dispiace x la chiusura di Kimonolabs,
ma quello che importa (almeno me) è disporre di metodologie semplici
(quindi a portata di tanti), veloci (poche azioni) per creare albi pop et
similia digitale.
Se in 3 passi semplici oggi possiamo creare tutti albi pop, domani possiamo
creare altre meraviglie di servizi digitali utili alla società.
Thanks Andrea, e Matteo per il lavoro che avete fatto di iniziazione.

Si anche secondo me un breve tutorial sui 3 step operativi sarebbe utile
per diffondere la prassi della realizzazione degli albi pop.

Il giorno 24 febbraio 2016 18:55, Andrea Borruso notifications@github.com
ha scritto:

**Comment by aborruso** [comment]
Ho iniziato a scrivere la prima parte del tutorial: https://github.com/aborruso/albo-pop/tree/master/code/GDriveGeneric/tutorial_ita

**Comment by Peppolhound** [comment]
Ciao Ragazzi,

sto cercando di creare l'albo Pop di Taranto. Sono riuscito a creare il foglio di scraping, ora sto cercando di pubblicarlo come risorsa RSS attraverso lo script di @mfortini, ma mi dà errore alla riga 159 (dove si inverte mese e giorno nel campo data). Sto cercando di risolvere da me, ma non sono abbastanza esperto, per cui sicuramente ci metterò un pò di tempo. Se riuscite a risolvere voi, mi fate sapere?

grazie,
g.

**Comment by aborruso** [comment]
Ciao @Peppolhound condividi qui, anche solo in lettura il tuo foglio elettronico?

**Comment by Peppolhound** [comment]
Certo @aborruso, 

ecco qui: https://docs.google.com/spreadsheets/d/10bc0KPlVyviY_-vpZIjvd8QkcKVbKL0hA_Wca1m60DY/edit?usp=sharing

**Comment by aborruso** [comment]
Ciao @Peppolhound ,
ho creato una [copia](https://docs.google.com/spreadsheets/d/1_cH-yUDX2iyLWeHTHpkt7M88eiTJvNjLyDV-D5eY7sE/edit?usp=sharing) del tuo e ho cambiato le query. Ho visto che era tutto stranamente lento e (anche per ragioni di fretta) ho reimpostato un po' tutto.
Le differenze principali:

- nelle impostazioni locali del foglio come "Locale" imposto United Kingdom. Mi è comodo perché le date in un RSS sono espresse in questo modo;
- raccolgo tutto nel foglio `raccoltaDati`;
- in questo faccio essenzialmente una sola interrogazione alla pagina html, perché mi concentro su una riga intera con XPATH `(//table)[2]//tr`;
- trasforma la data dal formato `05/01/2017` a  `Thu, 05 Jan 2017 00:00:00 +0200` non via script, ma direttamente con una funzione nello sheet (vedi colonna `pubDate` del foglio `raccoltaDati`);
- uso le [nuove specifiche](http://albopop.it/specs/) e raccolgo anche la data finale di pubblicazione, l'id, il tipo di documento;
- nel foglio meta inserisco altre info utili per classificare il feed secondo il nuovo schema;
- uso una versione dello script di @mfortini modificata.

Si ottiene un file RSS più ricco

```XML

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <atom:link href="https://script.google.com/macros/s/AKfycbzOLwHvfNA3ZnNu_v_lmFN2qWdlA2gtUegvt1564lKJsYEqBT2V/exec" rel="self" type="application/rss+xml" />
    <title>Albo pretorio POP Taranto</title>
    <link>https://script.google.com/macros/s/AKfycbzOLwHvfNA3ZnNu_v_lmFN2qWdlA2gtUegvt1564lKJsYEqBT2V/exec</link>
    <description>Versione non ufficiale dell'Albo Pretorio del Comune di Taranto</description>
    <language>it</language>
    <docs>http://albopop.it/comune/taranto/</docs>
    <webMaster>latuaemail@gmail.com (Il tuo nome e cognome)</webMaster>
    <category domain="http://albopop.it/specs#channel-category-type">Comune</category>
    <category domain="http://albopop.it/specs#channel-category-municipality">Taranto</category>
    <category domain="http://albopop.it/specs#channel-category-province">Taranto</category>
    <category domain="http://albopop.it/specs#channel-category-region">Puglia</category>
    <category domain="http://albopop.it/specs#channel-category-latitude">40.418056</category>
    <category domain="http://albopop.it/specs#channel-category-longitude">17.240833</category>
    <category domain="http://albopop.it/specs#channel-category-country">Italia</category>
    <category domain="http://albopop.it/specs#channel-category-name">Comune di Taranto</category>
    <category domain="http://albopop.it/specs#channel-category-uid">istat:073027</category>
    <xhtml:meta xmlns:xhtml="http://www.w3.org/1999/xhtml" name="robots" content="noindex" />
    <item>
      <title>“Programma Integrato di Riqualificazione delle Periferie – Ambito n. 1  Talsano-San Vito-Lama (P.I.R.P. n° 1). - Intervento denominato “U. M. I. 4  – Centro di aggregazione e verde attrezzato – Lotto n° 1: Sistemazione  stradale”. – OMOLOGAZIONE SPESA SOSTENUTA ED AMMISSIBILE.</title>
      <link>http://albopretorio.areavasta.csttaranto.it/web/albo-pretorio-sovracomunale/home?p_p_id=albopretorio_WAR_albopretorioportlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_albopretorio_WAR_albopretorioportlet_action=popupDettaglioAtto&amp;idAtto=22665</link>
      <description>“Programma Integrato di Riqualificazione delle Periferie – Ambito n. 1  Talsano-San Vito-Lama (P.I.R.P. n° 1). - Intervento denominato “U. M. I. 4  – Centro di aggregazione e verde attrezzato – Lotto n° 1: Sistemazione  stradale”. – OMOLOGAZIONE SPESA SOSTENUTA ED AMMISSIBILE.</description>
      <pubDate>Thu, 05 Jan 2017 00:00:00 +0200</pubDate>
      <guid>http://albopretorio.areavasta.csttaranto.it/web/albo-pretorio-sovracomunale/home?p_p_id=albopretorio_WAR_albopretorioportlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_albopretorio_WAR_albopretorioportlet_action=popupDettaglioAtto&amp;idAtto=22665</guid>
      <category domain="http://albopop.it/specs#item-category-pubEnd">Thu, 19 Jan 2017 00:00:00 +0200</category>
      <category domain="http://albopop.it/specs#item-category-pubStart">Thu, 05 Jan 2017 00:00:00 +0200</category>
      <category domain="http://albopop.it/specs#item-category-uid">22665</category>
      <category domain="http://albopop.it/specs#item-category-type">Determina</category>
    </item>
    <item>
```

Fai copia del mio foglio e dello script e usalo ai tuoi scopi.

Saluti,

a

**Comment by Peppolhound** [comment]
E noooo @aborruso, me l'hai fatto tutto tu....  mi hai tolto il gusto. ;)

**Comment by aborruso** [comment]
@Peppolhound avevo fretta, non capivo perché il tuo fosse inutilizzabile e l'unica soluzione mi sembrava rifarlo. Dai un occhio un po' alla query XPATH, allo script nuovo, ecc..

E fanne uno tutto tuo per Taranto, in modo che nel tempo te ne possa prendere cura e fare i dovuti check.
Non appena hai RSS pronto e/o altri canali di output apri una nuova issue di avviso qui.
