### ISSUE TITLE
Aggiungere noindex nei feed RSS che vengono generati

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#90]
Finché non abbiamo notizie certe sulla parte "legale" legata agli albi, è bene fare in modo che nulla possa essere indicizzato dai motori di ricerca.

Per evitare che un feed RSS venga indicizzato c'è da inserire nella sezione `channel` del feed la seguente stringa:

```
<xhtml:meta xmlns:xhtml="http://www.w3.org/1999/xhtml" name="robots" content="noindex" />
```

Questo può essere utile per tutti quelli che hanno scritto codice per generare RSS come @mfortini @piersoft @patperu @iltempe @cristianolongo

**Comment by iltempe** [comment]
Ottimo. Grazie @aborruso . ho appena aggiornato il mio repo inserendo questa stringa. https://github.com/iltempe/AlboPOPValDiBisenzio

**Comment by patperu** [comment]
Ok. https://github.com/patperu/albopop/commit/012d447a0
