### ISSUE TITLE
Da Gdrive a RSS: prima parte del tutorial

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#91]
Ciao,
come già annunciato @mfortini ha creato uno script che consente di creare un feed RSS a partire da un foglio elettronico di Google.

E' uno script che consente (quasi) a chiunque di essere autonomo nella creazione di un albo POP (e di tante altre cose).

Ho scritto una versione ancora incompleta e mai riletta di un tutorial in italiano. Se @mfortini , @iltempe , @piersoft  (o chiunque altro) vogliono aggiungere, correggere, modificare, ne sono ben lieto.

Si trova qui: https://github.com/aborruso/albo-pop/tree/master/code/GDriveGeneric/tutorial_ita

**Comment by piersoft** [comment]
scusa l'ignoranza ma come te lo modifico il readme? non mi appare la
matitina

Il giorno 28 febbraio 2016 16:53, Andrea Borruso notifications@github.com
ha scritto:

**Comment by piersoft** [comment]
perdono. mi è apparsa ;)

Il giorno 28 febbraio 2016 18:49, Francesco Piero Paolicelli <
piersoft2@gmail.com> ha scritto:

**Comment by piersoft** [comment]
fatto. ho aggiunto la descrizione. completatela

Il giorno 28 febbraio 2016 18:49, Francesco Piero Paolicelli <
piersoft2@gmail.com> ha scritto:

**Comment by aborruso** [comment]
Tutorial completato (ancora non riletto).

Le modifiche principali qui https://github.com/aborruso/albo-pop/tree/master/code/GDriveGeneric/tutorial_ita#costruiamo-il-nostro-piatto
