### ISSUE TITLE
Albo POP Erchie (provincia di Brindisi)

### ISSUE THREAD

**Issue by simoneversienti** [aborruso/albo-pop#92]
Buongiorno a tutti!
@aborruso c'è un Comune vicinissimo a Torre Santa Susanna che utilizza, per l'Albo Pretorio, la stessa piattaforma utilizzata per quello di Torre.
Il link è questo: http://dgegovpa.it/erchie/Albo/Albo.aspx
Possiamo riadattare il codice già realizzato per Torre Santa Susanna? Fammi sapere, buona giornata!

**Comment by aborruso** [comment]
Ciao @simoneversienti ecco il feed RSS di Erchie http://feeds.feedburner.com/Albopoperchie

Puoi dare una mano tu alle persone di Erchie a mettere in piedi il canale Telegram?

**Comment by simoneversienti** [comment]
Sisi

Il martedì 15 marzo 2016, Andrea Borruso notifications@github.com ha
scritto:
