### ISSUE TITLE
Richiesta albo per comune di Mesagne

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#93]
Appunto qui la richiesta ricevuta per http://www.comune.mesagne.br.it/albopretorio/

**Comment by piersoft** [comment]
ricevuta da parte di chi?

**Comment by ebergam** [comment]
Uguale uguale a quello di stamattina. Ci avrò messo 10 minuti con il nuovo metodo: http://feeds.feedburner.com/AlboPopMesagne

**Comment by aborruso** [comment]
@ebergam butta un occhio sempre ai dettagli :)

Di default la pagina source non è ordinata per data. Ho creato allora una colonna order e l'ho usata per la query del foglio clean

**Comment by ebergam** [comment]
Non l'avevo assolutamente notato, grazie!!

**Comment by aborruso** [comment]
@ebergam c'era un altro problema. La prima pagina, quella su cui viene fatto lo scraping, è quella con i post più vecchi.

Non esiste un permalink per aprire la pagina che lista gli atti pubblicati per data discendente, e il sito è "protetto da cooki" di sessione.

In bash allora ho clonato la pagina e faccio fare lo scraping lì.

Questo il nuovo URL http://feeds.feedburner.com/AlboMesagne e sotto lo script

``` bash
# imposto il cookie
curl -s -c $cartella/cookies.txt  "http://www.comune.mesagne.br.it/albopretorio/index.php?option=com_chronoconnectivity2&connectionname=albo_pretorio&start=&Itemid="  > /dev/null 2>&1

# scarico la pagina
curl -s -b $cartella/cookies.txt 'http://www.comune.mesagne.br.it/albopretorio/index.php?option=com_chronoconnectivity2&connectionname=albo_pretorio'  -H "Origin: http://www.comune.mesagne.br.it" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cache-Control: max-age=0" -H "Referer: http://www.comune.mesagne.br.it/albopretorio/index.php?option=com_chronoconnectivity2&connectionname=albo_pretorio&start=&Itemid=" -H "Connection: keep-alive" --data "filter_order=datainizio_atto&filter_order_Dir=desc&limit=50&limitstart=0" --compressed > $output/index.html
```

**Comment by aborruso** [comment]
@ebergam in realtà non è come dico, è l'URL che avevi usato nel tuo sheet che mi aveva tratto in inganno.

Se uso http://www.comune.mesagne.br.it/albopretorio/ è ordinato per data desc.

Come non detto :)

**Comment by ebergam** [comment]
Bene, già non ne avevo fatta una giusta con questo :) Quindi tutto ok? Questo il definitivo [http://feeds.feedburner.com/AlboMesagne](http://feeds.feedburner.com/AlboMesagne) ?

**Comment by aborruso** [comment]
L'ho messo in elenco http://albopop.it/comune/mesagne/  :)
