### ISSUE TITLE
Richiesta albo per comune di Valguarnera Caropepe

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#94]
Appunto qui la richiesta ricevuta per http://www.comune.valguarnera.en.it/albopretorio/index.php?option=com_chronoconnectivity2&Itemid=53

**Comment by ebergam** [comment]
Un inizio: https://docs.google.com/spreadsheets/d/1PXeAyf65w3rDUVyhTx6xklVjKLte2rEVvH3x2WItIoc/edit?usp=sharing
Se guardate i due fogli: importXML non mi funziona, con importHTML esce bene ma mancano i link

**Comment by aborruso** [comment]
On 2 March 2016 at 22:48, Enrico Bergamini notifications@github.com wrote:

> Se guardate i due fogli: importXML non mi funziona, con importHTML esce
> bene ma mancano i link

Ho fatto in maniera un po' sporca, ma ci siamo: foglio "andy"

## 

 Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

## 

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by ebergam** [comment]
Fantastico! Script aggiunto e la webapp dovrebbe girare bene, l'estensione RSS di chrome mi riconosce il feed. Ma dall'url della webapp dove trovo l'endpoint dell'rss? Pensavo fosse questo ma ovviamente non è validato: https://script.google.com/macros/s/AKfycbwOder71-iwhLAMZl7Oh5P-TvpyN5ifkcx7WSpXhdwZ-Xq21r0/exec

**Comment by aborruso** [comment]
Caro @ebergam,
tre cose importanti:
1. è l'URL del feed;
2. scegli il tuo accont gmail (ti verrà chiesta una sola volta l'autorizzazione)
3. imposta in questo modo le proprietà di accesso

Fatto

Uno dei motivi per cui non valida, è che il qualche modo il feed non è ancora pubblicamente accessibile.

![image](https://cloud.githubusercontent.com/assets/30607/13487611/7017b71e-e11b-11e5-8d7c-7db3dca359c9.png)

Facci sapere :)

**Comment by ebergam** [comment]
Ora è ok, avevo sbagliato a pubblicare l'app. Validator però non mi ha promosso :)
![albo](https://cloud.githubusercontent.com/assets/13796570/13487797/f647e86c-e11c-11e5-9514-ba3ba0d8a615.png)

**Comment by aborruso** [comment]
caro @ebergam dobbiamo completare la documentazione, e dire chiaramente di usare un modello di spreadsheet.

Mancavano queste meta

![image](https://cloud.githubusercontent.com/assets/30607/13487899/d49954f2-e11d-11e5-9b15-93860b0edef0.png)

Guarda adesso http://validator.w3.org/feed/check.cgi?url=https%3A//script.google.com/macros/s/AKfycbwOder71-iwhLAMZl7Oh5P-TvpyN5ifkcx7WSpXhdwZ-Xq21r0/exec

**Comment by ebergam** [comment]
Ah grande, ora ho capito! Habemus feed:)

**Comment by aborruso** [comment]
@ebergam che te ne pare di questa nuova modalità? Non è proprio basic, ma direi che possiamo dire che è rende quasi tutti autonomi nel fare queste cose

**Comment by ebergam** [comment]
@aborruso ti dirò che secondo me è ancora più pop! Via scripting da inserire in crontab sarebbe stato proibitivo ai non programmatori. Kimono era molto facile ma problematico, e in realtà credo che il livello di difficoltà tra kimono e questo metodo sia lo stesso, solo che così si usa un solo strumento (che è anche molto più stabile) e probabilmente molto più stabile. Complimenti!

**Comment by aborruso** [comment]
Complimenti a @mfortini

**Comment by aborruso** [comment]
Closed http://feeds.feedburner.com/AlbopopValguarneraCaropepe
