### ISSUE TITLE
GDriveGeneric: parsing errato delle date?

### ISSUE THREAD

**Issue by aborruso** [aborruso/albo-pop#95]
Caro @mfortini 
se guardi lo [sheet](https://docs.google.com/spreadsheets/d/1PXeAyf65w3rDUVyhTx6xklVjKLte2rEVvH3x2WItIoc/edit?usp=sharing) di Valguarnera, la data è espressa in dd/mm/yyyy, e nel caso specifico si legge "03/03/2016"

![image](https://cloud.githubusercontent.com/assets/30607/13488277/7e74836e-e120-11e5-9e1e-99bd3d1b1c6a.png)

L'[output RSS](https://script.google.com/macros/s/AKfycbwOder71-iwhLAMZl7Oh5P-TvpyN5ifkcx7WSpXhdwZ-Xq21r0/exec) però in output cambia la data:

![image](https://cloud.githubusercontent.com/assets/30607/13488341/e9df26ae-e120-11e5-9000-a49de5a5b245.png)

Che ne pensi?

**Comment by mfortini** [comment]
La data veniva convertita con la timezone GMT e l'orario 0:00 e quindi si poteva andare a finire nel giorno precedente nel caso es di conversione in GMT+1. Ho aggiunto l'ora 12:00 in modo da non poter incorrere nell'errore commit 24ca36b

**Comment by aborruso** [comment]
Grazie @mfortini , più tardi ne do comunicazione urbi et orbi
