### ISSUE TITLE
Errore in formattazione data

### ISSUE THREAD

**Issue by ebergam** [aborruso/albo-pop#96]
Se vedete l'albopop di Mesagne: [https://docs.google.com/spreadsheets/d/1TKY4T5MMBWPrZSh4geJ72RTdqiZsLbPhQ4JwqmEtNZs/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1TKY4T5MMBWPrZSh4geJ72RTdqiZsLbPhQ4JwqmEtNZs/edit?usp=sharing)
E il relativo output: [https://script.google.com/macros/s/AKfycbw1q-xE-NzcsBf2es3XwdxvPooVHvD9XdlFzJNABopXj8viM4g/exec](https://script.google.com/macros/s/AKfycbw1q-xE-NzcsBf2es3XwdxvPooVHvD9XdlFzJNABopXj8viM4g/exec)
La data compare in maniera errata 
`<pubDate>Sun, 02 Jul 2017 10:00:00 +0000</pubDate>`
Lo spreadsheet è in GMT0 e lo script usato è quello aggiornato. 

@mfortini che dici?

**Comment by mfortini** [comment]
Ho corretto lo script del foglio in questione abilitando la modifica della formattazione della data prima della conversione in Date() da javascript in modo che sia mm/dd/yyyy anziché dd/mm/yyyy
La questione da capire è come mai per alcuni Albi sia sufficiente la formattazione "italiana"

**Comment by aborruso** [comment]
@mfortini non appena hai caricato il codice sul repo, ne diamo notizia.

Grazie

**Comment by aborruso** [comment]
@mfortini  non appena hai caricato il codice sul repo, ne diamo notizia.

Grazie

**Comment by aborruso** [comment]
Sembra tutto ok.

Si è risolto modificando lo script originale in questo modo. Ma prima testare un po'

``` javascript
var pattern = /(\d{2})\/(\d{2})\/(\d{4})/;
var pDateFix=pDate.replace(pattern,'$2/$1/$3')
//var pDateFix=pDate;
```

**Comment by ebergam** [comment]
@mfortini @aborruso grazie!
