### ISSUE TITLE
Mettere a reddito gli Albi POP

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#98]
E' una provocazione.

**Comment by cristianolongo** [comment]
Ma neanche tanto. Sto valutando di offrire la realizzazione di un albo pop a chi si iscrive ad hackspace entro questo mese. Questo nasce sia dall'esigenza di trovare dei fondi per garantire la sopravvivenza dell'associazione, sia nella speranza che mettendoci dei soldi le persone tentino anche di metterlo a frutto.

**Comment by aborruso** [comment]
Mi piace molto che l'idea dell'albo possa essere usata come stimolo per associarsi ad hackspace, e che il frutto di una quota di associazione possa produrre come output un albo che poi servirà a tutti.

Se e quando sarà, dovremmo scrivere anche una nota negli albi creati in questo modo (albo sostenuto da Tizio Caio di hackspace).

**Comment by cristianolongo** [comment]
Se qualcuno ne sente la necessità possiamo fare un hangout, altrimenti procedo.

**Comment by cristianolongo** [comment]
Il 5 Aprile 2016 inizia la campagna #velofacciopagare che prevede che chi si iscrive ad Hackspace Catania entro il 5 Maggio dello stesso anno ha diritto di indicare una PA per la quale verrà realizzato l'albo pop
